export interface Ingredient {
  id: number;
  recipe_id: number;
  ingredient: string;
}

export interface Direction {
  id: number;
  recipe_id: number;
  instruction: string;
}

export interface Nutrition {
  recipe_id: number;
  calories?: string;
  fat?: string;
  saturated_fat?: string;
  unsaturated_fat?: string;
  carbs?: string;
  fiber?: string;
  sugar?: string;
  cholesterol?: string | "0";
  protein?: string;
  sodium?: string;
}

// Ingredients
export const ingredientsData: Ingredient[] = [
  // Appetizer (recipe_id 1)
  { id: 1, recipe_id: 1, ingredient: "1 cup diced tomatoes" },
  { id: 2, recipe_id: 1, ingredient: "2 tbsp olive oil" },
  { id: 3, recipe_id: 1, ingredient: "1 clove garlic, minced" },

  { id: 4, recipe_id: 2, ingredient: "12 mushrooms" },
  { id: 5, recipe_id: 2, ingredient: "1/4 cup breadcrumbs" },
  { id: 6, recipe_id: 2, ingredient: "2 tbsp parmesan cheese" },

  { id: 7, recipe_id: 3, ingredient: "Cherry tomatoes" },
  { id: 8, recipe_id: 3, ingredient: "Fresh mozzarella balls" },
  { id: 9, recipe_id: 3, ingredient: "Basil leaves" },

  { id: 10, recipe_id: 4, ingredient: "1 cup lemon juice" },
  { id: 11, recipe_id: 4, ingredient: "4 cups water" },
  { id: 12, recipe_id: 4, ingredient: "1/2 cup sugar" },
  {
    id: 23,
    recipe_id: 5,
    ingredient: "2 pounds red potatoes"
  },
  {
    id: 24,
    recipe_id: 5,
    ingredient: "3 hard-cooked eggs, chopped"
  },
  {
    id: 25,
    recipe_id: 5,
    ingredient: "0.5 cup sour cream"
  },
  {
    id: 26,
    recipe_id: 5,
    ingredient: "0.5 cup mayonnaise"
  },
  {
    id: 27,
    recipe_id: 5,
    ingredient: "0.5 (4 ounce) jar chopped pimento peppers"
  },
  {
    id: 28,
    recipe_id: 5,
    ingredient: "2 green onions, chopped"
  },
  {
    id: 29,
    recipe_id: 5,
    ingredient: "2 slices cooked bacon, chopped"
  },
  {
    id: 30,
    recipe_id: 5,
    ingredient: "2 tablespoons yellow mustard"
  },
  {
    id: 31,
    recipe_id: 5,
    ingredient: "1 tablespoon white sugar"
  },
  {
    id: 32,
    recipe_id: 5,
    ingredient: "1 tablespoon red wine vinegar"
  },
  {
    id: 33,
    recipe_id: 5,
    ingredient: "0.5 teaspoon salt"
  },
  {
    id: 34,
    recipe_id: 5,
    ingredient: "0.5 teaspoon ground black pepper"
  },
  {
    id: 35,
    recipe_id: 5,
    ingredient: "0.5 teaspoon celery seed"
  },
  {
    id: 36,
    recipe_id: 5,
    ingredient: "0.25 teaspoon garlic powder"
  },
  {
    id: 37,
    recipe_id: 5,
    ingredient: "1 pinch paprika, or as desired"
  },

  { id: 38, recipe_id: 6, ingredient: "2 cups cherries, pitted" },
  { id: 39, recipe_id: 6, ingredient: "0.6 cup white sugar" },
  { id: 40, recipe_id: 6, ingredient: "0.5 cup water" },
  { id: 41, recipe_id: 6, ingredient: "1 teaspoon ground cinnamon" },
  { id: 42, recipe_id: 6, ingredient: "1 cup sifted all-purpose flour" },
  { id: 43, recipe_id: 6, ingredient: "2 teaspoons baking powder" },
  { id: 44, recipe_id: 6, ingredient: "0.25 teaspoon salt" },
  { id: 45, recipe_id: 6, ingredient: "0.5 cup milk" },

  { id: 46, recipe_id: 7, ingredient: "4 limes, juiced" },
  { id: 47, recipe_id: 7, ingredient: "1 cup white sugar" },
  { id: 48, recipe_id: 7, ingredient: "2 sprigs fresh mint" },
  { id: 49, recipe_id: 7, ingredient: "0.5 gallon water" },
  { id: 50, recipe_id: 7, ingredient: "1 fresh jalapeno pepper, sliced" },

  { id: 51, recipe_id: 8, ingredient: "0.5 cup butter" },
  { id: 52, recipe_id: 8, ingredient: "2 (1 ounce) squares unsweetened chocolate, chopped" },
  { id: 53, recipe_id: 8, ingredient: "2 eggs" },
  { id: 54, recipe_id: 8, ingredient: "1 cup white sugar" },
  { id: 55, recipe_id: 8, ingredient: "1 teaspoon vanilla extract" },
  { id: 56, recipe_id: 8, ingredient: "3 tablespoons matzo meal" },
  { id: 57, recipe_id: 8, ingredient: "0.5 cup potato starch" },
  { id: 58, recipe_id: 8, ingredient: "0.5 teaspoon salt" },
  { id: 59, recipe_id: 8, ingredient: "0.5 cup chopped walnuts" },
  { id: 60, recipe_id: 8, ingredient: "0.5 cup semisweet chocolate chips" },

  { id: 61, recipe_id: 9, ingredient: "2 tomatoes, cut into chunks" },
  { id: 62, recipe_id: 9, ingredient: "1 large zucchini, cut into chunks" },
  { id: 63, recipe_id: 9, ingredient: "1 large yellow squash, cut into chunks" },
  { id: 64, recipe_id: 9, ingredient: "0.5 green bell pepper, diced" },
  { id: 65, recipe_id: 9, ingredient: "0.5 sweet red onion, chopped" },
  { id: 66, recipe_id: 9, ingredient: "2 cloves garlic, minced" },
  { id: 67, recipe_id: 9, ingredient: "1 teaspoon dried basil" },
  { id: 68, recipe_id: 9, ingredient: "0.5 teaspoon salt, or to taste" },
  { id: 69, recipe_id: 9, ingredient: "0.25 cup olive oil" },
  { id: 70, recipe_id: 9, ingredient: "0.25 cup red wine vinegar" },
  { id: 71, recipe_id: 9, ingredient: "3 tablespoons water" },

  { id: 72, recipe_id: 10, ingredient: "1 medium firm peach, halved and pitted" },
  { id: 73, recipe_id: 10, ingredient: "2 tablespoons unsalted butter" },
  { id: 74, recipe_id: 10, ingredient: "1 teaspoon light brown sugar" },
  { id: 75, recipe_id: 10, ingredient: "0.25 teaspoon ground cinnamon" },
  { id: 76, recipe_id: 10, ingredient: "2 scoops vanilla ice cream" },

  { id: 77, recipe_id: 12, ingredient: "1 cup white sugar" },
  { id: 78, recipe_id: 12, ingredient: "5 tablespoons butter, cut into slices" },
  { id: 79, recipe_id: 12, ingredient: "0.5 cup heavy cream" },
  { id: 80, recipe_id: 12, ingredient: "1 tablespoon heavy whipping cream" },
  { id: 81, recipe_id: 12, ingredient: "1 pinch sea salt to taste" },
  { id: 77, recipe_id: 12, ingredient: "1 cup white sugar" },
  { id: 78, recipe_id: 12, ingredient: "5 tablespoons butter, cut into slices" },
  { id: 79, recipe_id: 12, ingredient: "0.5 cup heavy cream" },
  { id: 80, recipe_id: 12, ingredient: "1 tablespoon heavy whipping cream" },
  { id: 81, recipe_id: 12, ingredient: "1 pinch sea salt to taste" },
  { id: 82, recipe_id: 14, ingredient: "0.5 cup water" },
  { id: 83, recipe_id: 14, ingredient: "0.33 cup dry lemonade-flavored drink mix" },
  { id: 84, recipe_id: 14, ingredient: "3 cups ice cubes" },
  { id: 85, recipe_id: 14, ingredient: "1 cup strawberries" },
  { id: 86, recipe_id: 15, ingredient: "1 cup boiling water" },
  { id: 87, recipe_id: 15, ingredient: "1 cup couscous" },
  { id: 88, recipe_id: 15, ingredient: "4 tomatoes" },
  { id: 89, recipe_id: 15, ingredient: "16 leaves fresh basil" },
  { id: 90, recipe_id: 15, ingredient: "8 ounces fresh mozzarella cheese, diced" },
  { id: 91, recipe_id: 15, ingredient: "0.25 cup balsamic vinegar, or to taste" },
  { id: 92, recipe_id: 19, ingredient: "0.25 cup butter" },
  { id: 93, recipe_id: 19, ingredient: "1.25 cups packed brown sugar" },
  { id: 94, recipe_id: 19, ingredient: "16 large marshmallows" },
  { id: 95, recipe_id: 19, ingredient: "2 tablespoons light corn syrup" },
  { id: 96, recipe_id: 19, ingredient: "1 dash salt" },
  { id: 97, recipe_id: 19, ingredient: "1 cup evaporated milk" },
  { id: 98, recipe_id: 19, ingredient: "0.5 cup chopped pecans, toasted" },
  { id: 99, recipe_id: 19, ingredient: "1 teaspoon vanilla extract" },
  { id: 100, recipe_id: 20, ingredient: "1.75 cups all-purpose flour" },
  { id: 101, recipe_id: 20, ingredient: "0.5 cup finely chopped crystallized ginger" },
  { id: 102, recipe_id: 20, ingredient: "1 teaspoon ground ginger" },
  { id: 103, recipe_id: 20, ingredient: "0.5 teaspoon baking powder" },
  { id: 104, recipe_id: 20, ingredient: "0.5 teaspoon baking soda" },
  { id: 105, recipe_id: 20, ingredient: "0.5 teaspoon salt" },
  { id: 106, recipe_id: 20, ingredient: "0.25 teaspoon ground nutmeg" },
  { id: 107, recipe_id: 20, ingredient: "0.5 cup unsalted butter, softened" },
  { id: 108, recipe_id: 20, ingredient: "1 cup brown sugar" },
  { id: 109, recipe_id: 20, ingredient: "1 large egg, at room temperature" },
  { id: 110, recipe_id: 20, ingredient: "1.5 teaspoons vanilla extract" },
  { id: 111, recipe_id: 20, ingredient: "1.5 cups finely chopped rhubarb" },
  { id: 112, recipe_id: 21, ingredient: "1 (15.25 ounce) package vanilla flavored cake mix" },
  { id: 113, recipe_id: 21, ingredient: "1 (15.25 ounce) package strawberry cake mix" },
  { id: 114, recipe_id: 21, ingredient: "6 large eggs, divided" },
  { id: 115, recipe_id: 21, ingredient: "2 cups water, divided" },
  { id: 116, recipe_id: 21, ingredient: "1 cup canola oil, divided" },
  { id: 117, recipe_id: 21, ingredient: "1.5 cups unsalted butter, softened" },
  { id: 118, recipe_id: 21, ingredient: "4 cups powdered sugar" },
  { id: 119, recipe_id: 21, ingredient: "6 tablespoons heavy whipping cream" },
  { id: 120, recipe_id: 21, ingredient: "2 teaspoons vanilla extract" },
  { id: 121, recipe_id: 21, ingredient: "3 cups freeze-dried strawberries" },
  { id: 122, recipe_id: 21, ingredient: "20 speculoos cookies (such as Lotus Biscoff®)" },
  { id: 123, recipe_id: 21, ingredient: "3 tablespoons unsalted butter, melted" },
  { id: 124, recipe_id: 23, ingredient: "1.5 cups water" },
  { id: 125, recipe_id: 23, ingredient: "1 cup uncooked basmati rice, rinsed and drained" },
  { id: 126, recipe_id: 23, ingredient: "0.75 pound plums, pitted and chopped" },
  { id: 127, recipe_id: 23, ingredient: "0.5 medium red onion, minced" },
  { id: 128, recipe_id: 23, ingredient: "3 habanero peppers, seeded and minced" },
  { id: 129, recipe_id: 23, ingredient: "3 tablespoons minced fresh cilantro" },
  { id: 130, recipe_id: 23, ingredient: "1 teaspoon sugar" },
  { id: 131, recipe_id: 23, ingredient: "0.75 pound boneless, skinless chicken breasts" },
  { id: 132, recipe_id: 23, ingredient: "2 teaspoons fresh rosemary, minced" },
  { id: 133, recipe_id: 23, ingredient: "salt and pepper to taste" },
  { id: 134, recipe_id: 23, ingredient: "2 teaspoons vegetable oil" },
  { id: 135, recipe_id: 24, ingredient: "1 (16 ounce) package penne pasta" },
  { id: 136, recipe_id: 24, ingredient: "2 cups shredded kale" },
  { id: 137, recipe_id: 24, ingredient: "2 medium carrots, shredded" },
  { id: 138, recipe_id: 24, ingredient: "1.5 cups cherry tomatoes, halved" },
  { id: 139, recipe_id: 24, ingredient: "1 cup sliced black olives, drained" },
  { id: 140, recipe_id: 24, ingredient: "1 cucumber, chopped" },
  { id: 141, recipe_id: 24, ingredient: "1 medium red bell pepper, chopped" },
  { id: 142, recipe_id: 24, ingredient: "0.5 shallot, chopped" },
  { id: 143, recipe_id: 24, ingredient: "1 cup Greek salad dressing" },
  { id: 144, recipe_id: 24, ingredient: "2 tablespoons mayonnaise" },
  { id: 145, recipe_id: 25, ingredient: "1 fresh peach, chopped" },
  { id: 146, recipe_id: 25, ingredient: "2 plums, pitted and chopped" },
  { id: 147, recipe_id: 25, ingredient: "1 cup chopped tomato" },
  { id: 148, recipe_id: 25, ingredient: "1 cup pitted and halved cherries" },
  { id: 149, recipe_id: 25, ingredient: "2 tablespoons chopped fresh parsley" },
  { id: 150, recipe_id: 25, ingredient: "1 teaspoon lemon zest" },
  { id: 151, recipe_id: 25, ingredient: "1 tablespoon lemon juice" },
  { id: 152, recipe_id: 25, ingredient: "1 clove garlic, minced" },
  { id: 153, recipe_id: 25, ingredient: "0.25 teaspoon salt" },
  { id: 154, recipe_id: 25, ingredient: "0.125 teaspoon ground black pepper" },
  { id: 155, recipe_id: 25, ingredient: "1 tablespoon extra-virgin olive oil" },
  { id: 156, recipe_id: 26, ingredient: "0.25 cup all-purpose flour" },
  { id: 157, recipe_id: 26, ingredient: "1.5 tablespoons brown sugar" },
  { id: 158, recipe_id: 26, ingredient: "0.5 teaspoon baking powder" },
  { id: 159, recipe_id: 26, ingredient: "1 dash salt" },
  { id: 160, recipe_id: 26, ingredient: "0.25 teaspoon cinnamon" },
  { id: 161, recipe_id: 26, ingredient: "0.25 teaspoon vanilla extract" },
  { id: 162, recipe_id: 26, ingredient: "3 tablespoons almond milk" },
  { id: 163, recipe_id: 26, ingredient: "0.5 tablespoon vegetable oil" },
  { id: 164, recipe_id: 26, ingredient: "3 tablespoons shredded zucchini" },
  { id: 165, recipe_id: 26, ingredient: "0.5 tablespoon chopped walnuts" },
  { id: 166, recipe_id: 27, ingredient: "1 cup biscuit baking mix" },
  { id: 167, recipe_id: 27, ingredient: "0.25 cup grated Parmesan cheese" },
  { id: 168, recipe_id: 27, ingredient: "1 teaspoon dried parsley" },
  { id: 169, recipe_id: 27, ingredient: "0.5 teaspoon garlic powder" },
  { id: 170, recipe_id: 27, ingredient: "0.5 teaspoon seasoning salt" },
  { id: 171, recipe_id: 27, ingredient: "0.5 teaspoon dried oregano" },
  { id: 172, recipe_id: 27, ingredient: "0.25 teaspoon salt" },
  { id: 173, recipe_id: 27, ingredient: "0.25 teaspoon ground black pepper" },
  { id: 174, recipe_id: 27, ingredient: "4 eggs" },
  { id: 175, recipe_id: 27, ingredient: "0.33300000429153 cup vegetable oil" },
  { id: 176, recipe_id: 27, ingredient: "0.25 cup grated onion" },
  { id: 177, recipe_id: 27, ingredient: "2 zucchini, thinly sliced" },
  { id: 178, recipe_id: 28, ingredient: "1 1/2 cups frozen blackberries" },
  { id: 179, recipe_id: 28, ingredient: "1/4 cup white sugar, or to taste" },
  { id: 180, recipe_id: 28, ingredient: "1 tablespoon fresh lemon juice" },
  { id: 181, recipe_id: 28, ingredient: "1/4 teaspoon freshly grated lemon zest, or to taste" },
  { id: 182, recipe_id: 28, ingredient: "1 teaspoon cornstarch" },
  { id: 183, recipe_id: 28, ingredient: "1 tablespoon water" },
  { id: 184, recipe_id: 28, ingredient: "1/2 cup unsalted butter, melted" },
  { id: 185, recipe_id: 28, ingredient: "1 cup firmly packed light brown sugar" },
  { id: 186, recipe_id: 28, ingredient: "1/2 teaspoon salt" },
  { id: 187, recipe_id: 28, ingredient: "1 egg, room temp" },
  { id: 188, recipe_id: 28, ingredient: "1 egg yolk, room temp" },
  { id: 189, recipe_id: 28, ingredient: "2 teaspoons vanilla extract" },
  { id: 190, recipe_id: 28, ingredient: "1/2 cup unsweetened cocoa powder" },
  { id: 191, recipe_id: 28, ingredient: "1/2 cup all-purpose flour" },
  { id: 192, recipe_id: 28, ingredient: "1/4 teaspoon baking soda" },
  { id: 193, recipe_id: 28, ingredient: "8 oz full fat cream cheese, room temp" },
  { id: 194, recipe_id: 28, ingredient: "1/3 cup white sugar" },
  { id: 195, recipe_id: 28, ingredient: "Pinch of salt" },
  { id: 196, recipe_id: 28, ingredient: "Pinch of ground nutmeg" },
  { id: 197, recipe_id: 28, ingredient: "1 egg white, room temp" },
  { id: 198, recipe_id: 28, ingredient: "2 teaspoons fresh lemon juice" },
  { id: 199, recipe_id: 28, ingredient: "1 teaspoon vanilla extract" },
  { id: 200, recipe_id: 28, ingredient: "3/4 cup heavy whipping cream, room temp" },
  { id: 201, recipe_id: 29, ingredient: "3 pounds fresh strawberries, hulled and sliced" },
  { id: 202, recipe_id: 29, ingredient: "0.25 cup white sugar" },
  { id: 203, recipe_id: 29, ingredient: "1 quart heavy cream" },
  { id: 204, recipe_id: 29, ingredient: "1 (6 ounce) container lemon yogurt" },
  { id: 205, recipe_id: 29, ingredient: "1 (3.3 ounce) package instant white chocolate pudding mix" },
  { id: 206, recipe_id: 29, ingredient: "2 tablespoons coconut-flavored rum, or to taste, divided" },
  { id: 207, recipe_id: 29, ingredient: "2 (16 ounce) prepared pound cakes, cubed" },
  { id: 208, recipe_id: 29, ingredient: "2 pints fresh blueberries, or as needed" },
  { id: 209, recipe_id: 30, ingredient: "2 cups blueberries" },
  { id: 210, recipe_id: 30, ingredient: "1 cup white sugar" },
  { id: 211, recipe_id: 30, ingredient: "0.25 cup water" },
  { id: 212, recipe_id: 30, ingredient: "1 tablespoon butter" },
  { id: 213, recipe_id: 30, ingredient: "1 cup all-purpose flour" },
  { id: 214, recipe_id: 30, ingredient: "2 teaspoons baking powder" },
  { id: 215, recipe_id: 30, ingredient: "0.125 teaspoon salt" },
  { id: 216, recipe_id: 30, ingredient: "0.5 cup milk" },
  { id: 231, recipe_id: 32, ingredient: "6 fresh raspberries, divided" },
  { id: 232, recipe_id: 32, ingredient: "1 tablespoon raspberry flavored liqueur" },
  { id: 233, recipe_id: 32, ingredient: "2 tablespoons vodka" },
  { id: 234, recipe_id: 32, ingredient: "0.75 cup lemonade" },
  { id: 235, recipe_id: 33, ingredient: "2.5 cups finely chopped rhubarb" },
  { id: 236, recipe_id: 33, ingredient: "0.5 cup white sugar" },
  { id: 237, recipe_id: 33, ingredient: "1 pinch salt" },
  { id: 238, recipe_id: 33, ingredient: "1 teaspoon lemon juice" },
  { id: 239, recipe_id: 33, ingredient: "2.5 cups all-purpose flour" },
  { id: 240, recipe_id: 33, ingredient: "1.5 teaspoons baking powder" },
  { id: 241, recipe_id: 33, ingredient: "0.75 teaspoon salt" },
  { id: 242, recipe_id: 33, ingredient: "0.5 teaspoon baking soda" },
  { id: 243, recipe_id: 33, ingredient: "0.5 cup unsalted butter, softened" },
  { id: 244, recipe_id: 33, ingredient: "0.25 cup vegetable oil" },
  { id: 245, recipe_id: 33, ingredient: "1.75 cups white sugar" },
  { id: 246, recipe_id: 33, ingredient: "3 large eggs, at room temperature" },
  { id: 247, recipe_id: 33, ingredient: "2 teaspoons vanilla extract" },
  { id: 248, recipe_id: 33, ingredient: "0.5 teaspoon almond extract" },
  { id: 249, recipe_id: 33, ingredient: "1.5 cups buttermilk, at room temperature" },
  { id: 250, recipe_id: 34, ingredient: "1 cup sugar" },
  { id: 251, recipe_id: 34, ingredient: "1 cup water" },
  { id: 252, recipe_id: 34, ingredient: "2 cups chopped mango" },
  { id: 253, recipe_id: 34, ingredient: "1 cup water" },
  { id: 254, recipe_id: 34, ingredient: "1 cup lemon juice" },
  { id: 255, recipe_id: 34, ingredient: "2 cups ice" },
  { id: 256, recipe_id: 35, ingredient: "2/3 \tcup mayonnaise" },
  { id: 257, recipe_id: 35, ingredient: "3\tTablespoons ketchup" },
  { id: 258, recipe_id: 35, ingredient: "2\tTablespoons sweet pickle relish" },
  { id: 259, recipe_id: 35, ingredient: "1 1/2 \tteaspoon vinegar" },
  { id: 260, recipe_id: 35, ingredient: "1/2 \tteaspoon sugar" },
  { id: 261, recipe_id: 35, ingredient: "1/4 \tteaspoon salt" },
  { id: 262, recipe_id: 35, ingredient: "1/4 teaspoon pepper optional" },
  { id: 274, recipe_id: 38, ingredient: "3 sprigs fresh dill" },
  { id: 275, recipe_id: 38, ingredient: "0.25 cup toasted pine nuts" },
  { id: 276, recipe_id: 38, ingredient: "0.5 cup fresh parsley" },
  { id: 277, recipe_id: 38, ingredient: "1 large clove garlic" },
  { id: 278, recipe_id: 38, ingredient: "0.25 cup freshly grated Parmesan cheese, or more to taste" },
  { id: 279, recipe_id: 38, ingredient: "3 tablespoons olive oil, divided, or as needed" },
  { id: 280, recipe_id: 38, ingredient: "0.25 medium lemon, or to taste" },
  { id: 281, recipe_id: 38, ingredient: "0.125 teaspoon salt, or to taste" },
  { id: 282, recipe_id: 38, ingredient: "0.125 teaspoon ground black pepper, or to taste" },
  { id: 283, recipe_id: 39, ingredient: "2 cups sweet kernel corn" },
  { id: 284, recipe_id: 39, ingredient: "0.75 cup diced tomato" },
  { id: 285, recipe_id: 39, ingredient: "0.5 cup diced orange bell pepper" },
  { id: 286, recipe_id: 39, ingredient: "0.5 cup chopped celery" },
  { id: 287, recipe_id: 39, ingredient: "0.25 cup diced red onion" },
  { id: 288, recipe_id: 39, ingredient: "1 clove garlic, minced" },
  { id: 289, recipe_id: 39, ingredient: "0.5 cup prepared ranch salad dressing" },
  { id: 290, recipe_id: 39, ingredient: "0.5 cup chopped fresh cilantro, divided" },
  { id: 291, recipe_id: 40, ingredient: "4 teaspoons canola oil, divided" },
  { id: 292, recipe_id: 40, ingredient: "2 eggs, beaten" },
  { id: 293, recipe_id: 40, ingredient: "2 carrots, chopped" },
  { id: 294, recipe_id: 40, ingredient: "salt and ground black pepper to taste" },
  { id: 295, recipe_id: 40, ingredient: "3 cloves garlic, crushed" },
  { id: 296, recipe_id: 40, ingredient: "1 cup frozen peas" },
  { id: 297, recipe_id: 40, ingredient: "4 scallions, minced" },
  { id: 298, recipe_id: 40, ingredient: "4 cups cooked rice" },
  { id: 299, recipe_id: 40, ingredient: "1 teaspoon soy sauce, or to taste" },
  { id: 300, recipe_id: 42, ingredient: "4 slices brioche bread" },
  { id: 301, recipe_id: 42, ingredient: "0.5 cup lemon curd" },
  { id: 302, recipe_id: 42, ingredient: "0.5 cup blueberries" },
  { id: 303, recipe_id: 42, ingredient: "2 large eggs" },
  { id: 304, recipe_id: 42, ingredient: "2 tablespoons milk" },
  { id: 305, recipe_id: 42, ingredient: "2 tablespoons unsalted butter" },
  { id: 306, recipe_id: 42, ingredient: "1 teaspoon confectioners' sugar" },
  { id: 307, recipe_id: 43, ingredient: "4 (8 ounce) boneless, skinless chicken breasts" },
  { id: 308, recipe_id: 43, ingredient: "0.25 cup red wine vinegar" },
  { id: 309, recipe_id: 43, ingredient: "2 teaspoons kosher salt" },
  { id: 310, recipe_id: 43, ingredient: "1 teaspoon freshly ground black pepper" },
  { id: 311, recipe_id: 43, ingredient: "0.25 teaspoon cayenne pepper" },
  { id: 312, recipe_id: 43, ingredient: "0.5 teaspoon dried thyme" },
  { id: 313, recipe_id: 43, ingredient: "0.5 teaspoon dried oregano" },
  { id: 314, recipe_id: 43, ingredient: "0.5 teaspoon dried rosemary" },
  { id: 315, recipe_id: 43, ingredient: "0.5 teaspoon garlic powder" },
  { id: 316, recipe_id: 43, ingredient: "0.25 cup olive oil" },
  { id: 317, recipe_id: 43, ingredient: "1 drizzle olive oil, or as needed" },
  { id: 318, recipe_id: 43, ingredient: "2 tablespoons chopped Italian parsley" },
  { id: 319, recipe_id: 43, ingredient: "2 tablespoons chopped fresh mint" },
  { id: 320, recipe_id: 43, ingredient: "1 cup full-fat Greek yogurt" },
  { id: 321, recipe_id: 43, ingredient: "8 ounces feta cheese" },
  { id: 322, recipe_id: 43, ingredient: "1 teaspoon finely crushed garlic, or to taste" },
  { id: 323, recipe_id: 43, ingredient: "1 tablespoon chopped fresh mint" },
  { id: 324, recipe_id: 43, ingredient: "1 teaspoon lemon zest" },
  { id: 325, recipe_id: 46, ingredient: "1\t(8 count) pack hotdogs" },
  { id: 326, recipe_id: 46, ingredient: "1/2\tcup garlic butter, melted" },
  { id: 327, recipe_id: 46, ingredient: "1\t(8 count) pack hotdog buns" },
  { id: 328, recipe_id: 46, ingredient: "2\tcups shredded cheese" },
  { id: 329, recipe_id: 47, ingredient: "3 teaspoons butter" },
  { id: 330, recipe_id: 47, ingredient: "3 ears fresh corn, husks and silks removed" },
  { id: 331, recipe_id: 47, ingredient: "1 teaspoon garlic powder" },
  { id: 332, recipe_id: 47, ingredient: "1 (15 ounce) can black beans, drained" },
  { id: 333, recipe_id: 47, ingredient: "0.25 cup chopped fresh cilantro" },
  { id: 334, recipe_id: 47, ingredient: "0.25 cup olive oil" },
  { id: 335, recipe_id: 47, ingredient: "2 tablespoons red wine vinegar" },
  { id: 336, recipe_id: 47, ingredient: "2 tablespoons lime juice" },
  { id: 337, recipe_id: 47, ingredient: "1.5 teaspoons minced garlic" },
  { id: 338, recipe_id: 47, ingredient: "1 teaspoon white sugar" },
  { id: 339, recipe_id: 47, ingredient: "0.5 teaspoon ground cumin" },
  { id: 340, recipe_id: 47, ingredient: "0.5 teaspoon chili powder" },
  { id: 341, recipe_id: 47, ingredient: "0.25 teaspoon salt" },
  { id: 342, recipe_id: 47, ingredient: "0.25 teaspoon black pepper" },
  { id: 343, recipe_id: 48, ingredient: "1 tablespoon olive oil" },
  { id: 344, recipe_id: 48, ingredient: "1 small onion, finely chopped" },
  { id: 345, recipe_id: 48, ingredient: "1 lb. ground sirloin" },
  { id: 346, recipe_id: 48, ingredient: "2 tablespoons low sodium Taco seasoning" },
  { id: 347, recipe_id: 48, ingredient: "8 ounces processed American cheese, such as Velveeta, cut into large chunks" },
  { id: 348, recipe_id: 48, ingredient: "1 (10 ounce) can diced tomatoes with green chiles, such as Rotel" },
  { id: 349, recipe_id: 48, ingredient: "8 to 10 crunchy taco shells" },
  { id: 350, recipe_id: 48, ingredient: "shredded iceberglettuce" },
  { id: 351, recipe_id: 48, ingredient: "Optional: desired toppings such as diced tomato, hot sauceand sour cream" },
  { id: 352, recipe_id: 49, ingredient: "1 cup white vinegar" },
  { id: 353, recipe_id: 49, ingredient: "0.5 cup white sugar" },
  { id: 354, recipe_id: 49, ingredient: "0.5 cup water" },
  { id: 355, recipe_id: 49, ingredient: "1 tablespoon chopped fresh dill" },
  { id: 356, recipe_id: 49, ingredient: "2 teaspoons salt" },
  { id: 357, recipe_id: 49, ingredient: "2 cucumbers, peeled and thinly sliced" },
  { id: 358, recipe_id: 49, ingredient: "0.33333334326744 cup sour cream" },
  { id: 359, recipe_id: 50, ingredient: "1 cup cornmeal" },
  { id: 360, recipe_id: 50, ingredient: "1 cup all-purpose flour, sifted" },
  { id: 361, recipe_id: 50, ingredient: "1/4 cup sugar" },
  { id: 362, recipe_id: 50, ingredient: "1 tablespoon baking powder" },
  { id: 363, recipe_id: 50, ingredient: "1 teaspoon salt" },
  { id: 364, recipe_id: 50, ingredient: "1 teaspoon pepper" },
  { id: 365, recipe_id: 50, ingredient: "1/4 cup vegetable oil" },
  { id: 366, recipe_id: 50, ingredient: "2 jalapenos, seeded and diced" },
  { id: 367, recipe_id: 50, ingredient: "1 small yellow onion, minced" },
  { id: 368, recipe_id: 50, ingredient: "3/4 cup shredded sharp Cheddar cheese, divided" },
  { id: 369, recipe_id: 50, ingredient: "1 egg, beaten" },
  { id: 370, recipe_id: 50, ingredient: "1 cup buttermilk" },
  { id: 371, recipe_id: 50, ingredient: "1 tablespoon vegetable oil, or as needed" },
  { id: 372, recipe_id: 51, ingredient: "1 recipe pastry for a single 9-inch pie crust" },
  { id: 373, recipe_id: 51, ingredient: "1 (28 ounce) can sliced peaches, drained" },
  { id: 374, recipe_id: 51, ingredient: "1 cup white sugar" },
  { id: 375, recipe_id: 51, ingredient: "1 egg" },
  { id: 376, recipe_id: 51, ingredient: "1 tablespoon all-purpose flour" },
  { id: 377, recipe_id: 51, ingredient: "1 teaspoon butter" },
  { id: 378, recipe_id: 51, ingredient: "0.25 teaspoon ground cinnamon, or to taste" },
  { id: 379, recipe_id: 61, ingredient: "0.75 cup white sugar" },
  { id: 380, recipe_id: 61, ingredient: "2 tablespoons all-purpose flour" },
  { id: 381, recipe_id: 61, ingredient: "0.25 teaspoon salt" },
  { id: 382, recipe_id: 61, ingredient: "1 cup sour cream" },
  { id: 383, recipe_id: 61, ingredient: "1 egg, lightly beaten" },
  { id: 384, recipe_id: 61, ingredient: "0.5 teaspoon vanilla extract" },
  { id: 385, recipe_id: 61, ingredient: "2 cups sliced peaches" },
  { id: 386, recipe_id: 61, ingredient: "1 unbaked pie crust" },
  { id: 387, recipe_id: 61, ingredient: "1/3 cup all-purpose flour" },
  { id: 388, recipe_id: 61, ingredient: "1/3 cup white sugar" },
  { id: 389, recipe_id: 61, ingredient: "1 teaspoon ground cinnamon" },
  { id: 390, recipe_id: 61, ingredient: "1/4 cup unsalted butter" },
  { id: 391, recipe_id: 63, ingredient: "1 cup all-purpose flour" },
  { id: 392, recipe_id: 63, ingredient: "0.25 cup packed brown sugar" },
  { id: 393, recipe_id: 63, ingredient: "0.5 cup chopped walnuts" },
  { id: 394, recipe_id: 63, ingredient: "0.5 cup butter, melted" },
  { id: 395, recipe_id: 63, ingredient: "2 cups sliced fresh strawberries" },
  { id: 396, recipe_id: 63, ingredient: "1 cup white sugar" },
  { id: 397, recipe_id: 63, ingredient: "6 tablespoons pasteurized liquid egg whites" },
  { id: 398, recipe_id: 63, ingredient: "2 tablespoons lemon juice" },
  { id: 399, recipe_id: 63, ingredient: "1 cup heavy whipping cream, whipped" },
  { id: 400, recipe_id: 64, ingredient: "1 (14 ounce) can sweetened condensed milk" },
  { id: 401, recipe_id: 64, ingredient: "1 (8 ounce) package cream cheese, softened" },
  { id: 402, recipe_id: 64, ingredient: "1 (12 ounce) container frozen whipped topping, thawed" },
  { id: 403, recipe_id: 64, ingredient: "1 (20 ounce) can crushed pineapple, drained" },
  { id: 404, recipe_id: 64, ingredient: "1.5 cups chopped pecans" },
  { id: 405, recipe_id: 64, ingredient: "2 (9 inch) prepared graham cracker crusts" },
  { id: 406, recipe_id: 65, ingredient: "1/3 cup white sugar" },
  { id: 407, recipe_id: 65, ingredient: "1 teaspoon instant coffee powder" },
  { id: 408, recipe_id: 65, ingredient: "1 tablespoon unsweetened cocoa powder" },
  { id: 409, recipe_id: 65, ingredient: "1 teaspoon pure vanilla extract" },
  { id: 410, recipe_id: 65, ingredient: "3 tablespoons coffee liqueur" },
  { id: 411, recipe_id: 65, ingredient: "2 cups cold heavy cream" },
  { id: 412, recipe_id: 65, ingredient: "12 ounces mascarpone cheese or cream cheese" },
  { id: 413, recipe_id: 65, ingredient: "4 (8 ounce) packages chocolate chip cookies (about 45), such as Tate’s Bake Shop Double Chocolate Chip Cookies" },
  { id: 414, recipe_id: 66, ingredient: "4 cups coarsely chopped seedless watermelon" },
  { id: 415, recipe_id: 66, ingredient: "4 cups seedless red grapes, halved" },
  { id: 416, recipe_id: 66, ingredient: "2 tablespoons grated lemon zest" },
  { id: 417, recipe_id: 66, ingredient: "2 tablespoons grated lime zest" },
  { id: 418, recipe_id: 67, ingredient: "2 cups diced seeded watermelon" },
  { id: 419, recipe_id: 67, ingredient: "1 avocado - peeled, pitted, and diced" },
  { id: 420, recipe_id: 67, ingredient: "0.25 cup diced red onion" },
  { id: 421, recipe_id: 67, ingredient: "2 tablespoons lemon juice" },
  { id: 422, recipe_id: 67, ingredient: "0.5 habanero pepper, seeded and minced" },
  { id: 423, recipe_id: 67, ingredient: "1.5 teaspoons dried parsley" },
  { id: 424, recipe_id: 67, ingredient: "0.25 teaspoon salt, or to taste" },
  { id: 425, recipe_id: 68, ingredient: "4 cups cubed watermelon" },
  { id: 426, recipe_id: 68, ingredient: "4 cups fresh baby spinach, torn" },
  { id: 427, recipe_id: 68, ingredient: "2 large avocados - peeled, pitted, and diced" },
  { id: 428, recipe_id: 68, ingredient: "0.25 cup walnut oil" },
  { id: 429, recipe_id: 68, ingredient: "0.25 cup olive oil" },
  { id: 430, recipe_id: 68, ingredient: "1 lime, juiced" },
  { id: 431, recipe_id: 68, ingredient: "0.5 teaspoon sweet paprika" },
  { id: 432, recipe_id: 71, ingredient: "1\tTablespoon olive oil" },
  { id: 433, recipe_id: 71, ingredient: "2\tpoblano peppers,thinly sliced" },
  { id: 434, recipe_id: 71, ingredient: "1\tyellow or orange bell pepper, thinly sliced" },
  { id: 435, recipe_id: 71, ingredient: "1\twhite onion, thinly sliced" },
  { id: 436, recipe_id: 71, ingredient: "1 1/2\tteaspoon chili powder" },
  { id: 437, recipe_id: 71, ingredient: "1/2 \tteaspoon ground cumin" },
  { id: 438, recipe_id: 71, ingredient: "1/4 \tteaspoon garlic powder" },
  { id: 439, recipe_id: 71, ingredient: "3/4\tteaspoon kosher salt" },
  { id: 440, recipe_id: 71, ingredient: "1/2 \tteaspoon freshly ground black pepper" },
  { id: 441, recipe_id: 71, ingredient: "2 1/2 \ttablespoons butter" },
  { id: 442, recipe_id: 71, ingredient: "2\ttablespoons all-purpose flour" },
  { id: 443, recipe_id: 71, ingredient: "1\t(10 ounce) can diced tomatoes and green chiles" },
  { id: 444, recipe_id: 71, ingredient: "1 1/4 \tcup chicken broth" },
  { id: 445, recipe_id: 71, ingredient: "2 1/2\tcups shredded rotisserie chicken" },
  { id: 446, recipe_id: 71, ingredient: "1\t15 ounce can pinto beans, drained and rinsed" },
  { id: 447, recipe_id: 71, ingredient: "2\tcups sharp Cheddar cheese, divided" },
  { id: 448, recipe_id: 71, ingredient: "3\tcups broken tortilla chips" },
  { id: 449, recipe_id: 71, ingredient: "Optional toppings such as lettuce, cilantro, sour cream, salsa and hot sauce" },
  { id: 450, recipe_id: 72, ingredient: "1.5 cups sliced fresh strawberries" },
  { id: 451, recipe_id: 72, ingredient: "2 tablespoons white sugar" },
  { id: 452, recipe_id: 72, ingredient: "1 cup all-purpose flour" },
  { id: 453, recipe_id: 72, ingredient: "2 tablespoons white sugar" },
  { id: 454, recipe_id: 72, ingredient: "0.75 teaspoon baking powder" },
  { id: 455, recipe_id: 72, ingredient: "0.125 teaspoon salt" },
  { id: 456, recipe_id: 72, ingredient: "2 tablespoons butter" },
  { id: 457, recipe_id: 72, ingredient: "3 tablespoons 2% milk" },
  { id: 458, recipe_id: 72, ingredient: "1 egg yolk, beaten" },
  { id: 459, recipe_id: 72, ingredient: "0.75 teaspoon lemon zest" },
  { id: 460, recipe_id: 72, ingredient: "0.25 cup nonfat plain yogurt" },
  { id: 461, recipe_id: 72, ingredient: "0.25 cup reduced-fat sour cream" },
  { id: 462, recipe_id: 72, ingredient: "1 tablespoon agave nectar" },
  { id: 463, recipe_id: 72, ingredient: "0.5 teaspoon lemon zest" },
  { id: 464, recipe_id: 72, ingredient: "0.33333334326744 cup heavy whipping cream" },
  { id: 465, recipe_id: 72, ingredient: "1 teaspoon white sugar" },
  { id: 466, recipe_id: 73, ingredient: "12\tsourdough english muffins, cut into cubes" },
  { id: 467, recipe_id: 73, ingredient: "10\tTablespoons butter, divided" },
  { id: 468, recipe_id: 73, ingredient: "2\tTablespoons dijon mustard" },
  { id: 469, recipe_id: 73, ingredient: "8\teggs" },
  { id: 470, recipe_id: 73, ingredient: "1 1/4 \tcup half and half" },
  { id: 471, recipe_id: 73, ingredient: "1 1/2\tteaspoon kosher salt" },
  { id: 472, recipe_id: 73, ingredient: "3/4 \tteaspoon pepper" },
  { id: 473, recipe_id: 73, ingredient: "1/2 \tpound deli sliced ham" },
  { id: 474, recipe_id: 73, ingredient: "3\tcups grated swiss or gruyere cheese" },
  { id: 475, recipe_id: 73, ingredient: "2\tcups milk" },
  { id: 476, recipe_id: 73, ingredient: "4\tTablespoons all-purpose flour" },
  { id: 477, recipe_id: 73, ingredient: "1/8\tteaspoon grated nutmeg" },
  { id: 478, recipe_id: 73, ingredient: "3\ttablespoons grated parmesan cheese" },
  { id: 495, recipe_id: 77, ingredient: "2 cups dark chocolate chips (such as Ghriradelli® 60% Cacao Bittersweet Chocolate Chips)" },
  { id: 496, recipe_id: 77, ingredient: "1 1/2 cups white sugar" },
  { id: 497, recipe_id: 77, ingredient: "1/4 cup water" },
  { id: 498, recipe_id: 77, ingredient: "3 tablespoons light corn syrup" },
  { id: 499, recipe_id: 77, ingredient: "1/4 teaspoon salt" },
  { id: 500, recipe_id: 77, ingredient: "1 1/2 cups heavy cream" },
  { id: 501, recipe_id: 77, ingredient: "2 teaspoons vanilla extract" },
  { id: 502, recipe_id: 77, ingredient: "3 tablespoons Irish Cream liqueur (such as Bailey's)" },
  { id: 503, recipe_id: 77, ingredient: "3 tablespoons unsalted butter" },
  { id: 504, recipe_id: 77, ingredient: "1 (11.2 ounce) bottle stout beer (such as Guinness ™ )" },
  { id: 505, recipe_id: 77, ingredient: "1 tablespoon dark brown sugar" },
  { id: 506, recipe_id: 77, ingredient: "1 3/4 cups all-purpose flour" },
  { id: 507, recipe_id: 77, ingredient: "1 cup unsweetened dark cocoa powder (such as Hershey's® Special Dark)" },
  { id: 508, recipe_id: 77, ingredient: "1 teaspoon baking powder" },
  { id: 509, recipe_id: 77, ingredient: "1 teaspoon baking soda" },
  { id: 510, recipe_id: 77, ingredient: "3/4 teaspoon salt" },
  { id: 511, recipe_id: 77, ingredient: "1/2 cup unsalted butter, softened" },
  { id: 512, recipe_id: 77, ingredient: "3 tablespoons vegetable oil" },
  { id: 513, recipe_id: 77, ingredient: "1 cup firmly packed dark brown sugar" },
  { id: 514, recipe_id: 77, ingredient: "1/2 cup white sugar" },
  { id: 515, recipe_id: 77, ingredient: "2 large eggs, room temp" },
  { id: 516, recipe_id: 77, ingredient: "1 cup full-fat sour cream, at room temperature" },
  { id: 517, recipe_id: 77, ingredient: "2 teaspoons vanilla extract" },
  { id: 518, recipe_id: 78, ingredient: "2 large zucchini, trimmed and halved lengthwise" },

  { id: 519, recipe_id: 78, ingredient: "4 ripe tomatoes, cored" },
  { id: 520, recipe_id: 78, ingredient: "4 fresh basil leaves" },
  { id: 521, recipe_id: 78, ingredient: "0.25 cup olive oil" },
  { id: 522, recipe_id: 78, ingredient: "1 teaspoon crushed garlic" },
  { id: 523, recipe_id: 78, ingredient: "1 teaspoon dried Italian herb seasoning" },
  { id: 524, recipe_id: 78, ingredient: "1 teaspoon white sugar" },
  { id: 525, recipe_id: 78, ingredient: "0.75 teaspoon salt" },
  { id: 526, recipe_id: 78, ingredient: "0.5 teaspoon ground black pepper" },
  { id: 527, recipe_id: 78, ingredient: "3 tablespoons olive oil" },
  { id: 528, recipe_id: 78, ingredient: "1 onion, diced" },
  { id: 529, recipe_id: 78, ingredient: "1 pound bulk sweet Italian sausage" },
  { id: 530, recipe_id: 78, ingredient: "0.25 cup grated Parmesan cheese" },
  { id: 531, recipe_id: 78, ingredient: "1 cup grated mozzarella cheese" },

  { "id": 532, "recipe_id": 11, "ingredient": "1 1/2 cups all-purpose flour" },
  { "id": 533, "recipe_id": 11, "ingredient": "3 1/2 teaspoons baking powder" },
  { "id": 534, "recipe_id": 11, "ingredient": "1 teaspoon salt" },
  { "id": 535, "recipe_id": 11, "ingredient": "1 tablespoon white sugar" },
  { "id": 536, "recipe_id": 11, "ingredient": "1 1/4 cups milk" },
  { "id": 537, "recipe_id": 11, "ingredient": "1 egg" },
  { "id": 538, "recipe_id": 11, "ingredient": "3 tablespoons butter, melted" },
  { "id": 539, "recipe_id": 11, "ingredient": "1 teaspoon vanilla extract (optional)" },

  { "id": 540, "recipe_id": 13, "ingredient": "4 slices of bread" },
  { "id": 541, "recipe_id": 13, "ingredient": "2 eggs" },
  { "id": 542, "recipe_id": 13, "ingredient": "1/2 cup milk" },
  { "id": 543, "recipe_id": 13, "ingredient": "1 teaspoon vanilla extract" },
  { "id": 544, "recipe_id": 13, "ingredient": "1/2 teaspoon ground cinnamon" },
  { "id": 545, "recipe_id": 13, "ingredient": "Pinch of salt" },
  { "id": 546, "recipe_id": 13, "ingredient": "2 tablespoons butter" },
  { "id": 547, "recipe_id": 13, "ingredient": "Maple syrup, for serving (optional)" },

  { "id": 548, "recipe_id": 16, "ingredient": "2 slices of whole-grain bread" },
  { "id": 549, "recipe_id": 16, "ingredient": "1 ripe avocado" },
  { "id": 550, "recipe_id": 16, "ingredient": "1 teaspoon lemon juice" },
  { "id": 551, "recipe_id": 16, "ingredient": "Salt, to taste" },
  { "id": 552, "recipe_id": 16, "ingredient": "Black pepper, to taste" },
  { "id": 553, "recipe_id": 16, "ingredient": "Optional toppings: cherry tomatoes, radish slices, microgreens, or a poached egg" },

  { "id": 554, "recipe_id": 17, "ingredient": "2 English muffins, split" },
  { "id": 555, "recipe_id": 17, "ingredient": "4 slices of Canadian bacon or ham" },
  { "id": 556, "recipe_id": 17, "ingredient": "4 large eggs" },
  { "id": 557, "recipe_id": 17, "ingredient": "2 tablespoons white vinegar" },
  { "id": 558, "recipe_id": 17, "ingredient": "Hollandaise sauce (about 1/2 cup)" },
  { "id": 559, "recipe_id": 17, "ingredient": "Salt, to taste" },
  { "id": 560, "recipe_id": 17, "ingredient": "Black pepper, to taste" },
  { "id": 561, "recipe_id": 17, "ingredient": "Chopped chives or parsley, for garnish (optional)" },

  { "id": 562, "recipe_id": 18, "ingredient": "2 large flour tortillas" },
  { "id": 563, "recipe_id": 18, "ingredient": "4 large eggs" },
  { "id": 564, "recipe_id": 18, "ingredient": "1/4 cup milk" },
  { "id": 565, "recipe_id": 18, "ingredient": "1/2 cup cooked breakfast sausage or bacon, chopped" },
  { "id": 566, "recipe_id": 18, "ingredient": "1/2 cup shredded cheddar cheese" },
  { "id": 567, "recipe_id": 18, "ingredient": "1/4 cup diced bell peppers" },
  { "id": 568, "recipe_id": 18, "ingredient": "1/4 cup diced onions" },
  { "id": 569, "recipe_id": 18, "ingredient": "Salt and black pepper, to taste" },
  { "id": 570, "recipe_id": 18, "ingredient": "Optional: salsa, avocado, or sour cream for serving" },

  { "id": 571, "recipe_id": 22, "ingredient": "10 fresh mint leaves" },
  { "id": 572, "recipe_id": 22, "ingredient": "1/2 lime, cut into 4 wedges" },
  { "id": 573, "recipe_id": 22, "ingredient": "2 tablespoons white sugar" },
  { "id": 574, "recipe_id": 22, "ingredient": "1 cup ice cubes" },
  { "id": 575, "recipe_id": 22, "ingredient": "1 1/2 ounces white rum" },
  { "id": 576, "recipe_id": 22, "ingredient": "1/2 cup club soda" },

  { "id": 578, "recipe_id": 41, "ingredient": "18-20 grams finely ground espresso coffee" },
  { "id": 579, "recipe_id": 41, "ingredient": "2 ounces hot water" },

  { "id": 585, "recipe_id": 76, "ingredient": "2 tablespoons ground turmeric" },
  { "id": 586, "recipe_id": 76, "ingredient": "1 tablespoon ground coriander" },
  { "id": 587, "recipe_id": 76, "ingredient": "1 tablespoon ground cumin" },
  { "id": 588, "recipe_id": 76, "ingredient": "1 teaspoon ground ginger" },
  { "id": 589, "recipe_id": 76, "ingredient": "1 teaspoon ground cinnamon" },
  { "id": 590, "recipe_id": 76, "ingredient": "1/2 teaspoon cayenne pepper" },
  { "id": 591, "recipe_id": 76, "ingredient": "1/2 teaspoon ground black pepper" },
  { "id": 592, "recipe_id": 76, "ingredient": "1/2 teaspoon ground cardamom" },

  { "id": 593, "recipe_id": 78, "ingredient": "4 medium zucchinis, halved lengthwise and seeds scooped out" },
  { "id": 594, "recipe_id": 78, "ingredient": "1/2 pound ground beef or turkey" },
  { "id": 595, "recipe_id": 78, "ingredient": "1 small onion, diced" },
  { "id": 596, "recipe_id": 78, "ingredient": "2 cloves garlic, minced" },
  { "id": 597, "recipe_id": 78, "ingredient": "1 cup cooked rice or quinoa" },
  { "id": 598, "recipe_id": 78, "ingredient": "1 cup marinara sauce" },
  { "id": 599, "recipe_id": 78, "ingredient": "1/2 cup shredded mozzarella cheese" },
  { "id": 600, "recipe_id": 78, "ingredient": "1/4 cup grated Parmesan cheese" },
  { "id": 601, "recipe_id": 78, "ingredient": "1 teaspoon dried Italian herbs" },
  { "id": 602, "recipe_id": 78, "ingredient": "Salt and pepper, to taste" },

  { "id": 603, "recipe_id": 75, "ingredient": "2 tablespoons olive oil" },
  { "id": 604, "recipe_id": 75, "ingredient": "1 onion, diced" },
  { "id": 605, "recipe_id": 75, "ingredient": "2 cloves garlic, minced" },
  { "id": 606, "recipe_id": 75, "ingredient": "2 carrots, diced" },
  { "id": 607, "recipe_id": 75, "ingredient": "2 celery stalks, diced" },
  { "id": 608, "recipe_id": 75, "ingredient": "1 zucchini, diced" },
  { "id": 609, "recipe_id": 75, "ingredient": "1 can (14 oz) diced tomatoes" },
  { "id": 610, "recipe_id": 75, "ingredient": "4 cups vegetable or chicken broth" },
  { "id": 611, "recipe_id": 75, "ingredient": "1 can (15 oz) cannellini beans, drained and rinsed" },
  { "id": 612, "recipe_id": 75, "ingredient": "1 teaspoon dried Italian herbs" },
  { "id": 613, "recipe_id": 75, "ingredient": "Salt and pepper, to taste" },
  { "id": 614, "recipe_id": 75, "ingredient": "1/2 cup small pasta (like ditalini)" },
  { "id": 615, "recipe_id": 75, "ingredient": "Grated Parmesan cheese, for serving" },
  { "id": 616, "recipe_id": 75, "ingredient": "Fresh parsley, chopped, for garnish" },

  { "id": 617, "recipe_id": 70, "ingredient": "8 ounces tortilla chips" },
  { "id": 618, "recipe_id": 70, "ingredient": "1 cup shredded cheddar cheese" },
  { "id": 619, "recipe_id": 70, "ingredient": "1/2 cup cooked ground beef or chicken (optional)" },
  { "id": 620, "recipe_id": 70, "ingredient": "1/4 cup diced tomatoes" },
  { "id": 621, "recipe_id": 70, "ingredient": "1/4 cup sliced jalapeños" },
  { "id": 622, "recipe_id": 70, "ingredient": "1/4 cup black olives, sliced" },
  { "id": 623, "recipe_id": 70, "ingredient": "1/4 cup diced onions" },
  { "id": 624, "recipe_id": 70, "ingredient": "Sour cream, guacamole, and salsa for serving" },

  { "id": 625, "recipe_id": 69, "ingredient": "4 cups shredded cabbage" },
  { "id": 626, "recipe_id": 69, "ingredient": "1 cup shredded carrots" },
  { "id": 627, "recipe_id": 69, "ingredient": "1/2 cup mayonnaise" },
  { "id": 628, "recipe_id": 69, "ingredient": "2 tablespoons apple cider vinegar" },
  { "id": 629, "recipe_id": 69, "ingredient": "1 tablespoon sugar" },
  { "id": 630, "recipe_id": 69, "ingredient": "Salt and pepper, to taste" },

  { "id": 631, "recipe_id": 62, "ingredient": "2 slices of bread" },
  { "id": 632, "recipe_id": 62, "ingredient": "2 slices of cheddar cheese" },
  { "id": 633, "recipe_id": 62, "ingredient": "1 tablespoon butter, softened" },

  { "id": 634, "recipe_id": 36, "ingredient": "1 large egg at room temperature" },
  { "id": 635, "recipe_id": 36, "ingredient": "1 tablespoon Dijon mustard" },
  { "id": 636, "recipe_id": 36, "ingredient": "1 tablespoon white wine vinegar" },
  { "id": 637, "recipe_id": 36, "ingredient": "1/2 teaspoon kosher salt" },
  { "id": 638, "recipe_id": 36, "ingredient": "1 cup neutral oil (such as vegetable or canola oil)" },
  { "id": 639, "recipe_id": 36, "ingredient": "1 tablespoon fresh lemon juice" },

  { "id": 640, "recipe_id": 55, "ingredient": "2 1/2 cups all-purpose flour" },
  { "id": 641, "recipe_id": 55, "ingredient": "1 teaspoon salt" },
  { "id": 642, "recipe_id": 55, "ingredient": "1 cup unsalted butter, chilled and cut into cubes" },
  { "id": 643, "recipe_id": 55, "ingredient": "1/4 to 1/2 cup ice water" },
  { "id": 644, "recipe_id": 55, "ingredient": "6-7 medium apples, peeled, cored, and sliced" },
  { "id": 645, "recipe_id": 55, "ingredient": "3/4 cup granulated sugar" },
  { "id": 646, "recipe_id": 55, "ingredient": "1/4 cup brown sugar" },
  { "id": 647, "recipe_id": 55, "ingredient": "1 teaspoon ground cinnamon" },
  { "id": 648, "recipe_id": 55, "ingredient": "1/4 teaspoon ground nutmeg" },
  { "id": 649, "recipe_id": 55, "ingredient": "1/4 teaspoon salt" },
  { "id": 650, "recipe_id": 55, "ingredient": "1 tablespoon lemon juice" },
  { "id": 651, "recipe_id": 55, "ingredient": "1 tablespoon unsalted butter, for dotting on top" },
  { "id": 652, "recipe_id": 55, "ingredient": "1 egg, beaten (for egg wash)" },
  { "id": 653, "recipe_id": 55, "ingredient": "1 tablespoon coarse sugar, for sprinkling (optional)" },

  { "id": 654, "recipe_id": 56, "ingredient": "1 (9-inch) unbaked pie crust" },
  { "id": 655, "recipe_id": 56, "ingredient": "3/4 cup granulated sugar" },
  { "id": 656, "recipe_id": 56, "ingredient": "1/2 teaspoon salt" },
  { "id": 657, "recipe_id": 56, "ingredient": "1 teaspoon ground cinnamon" },
  { "id": 658, "recipe_id": 56, "ingredient": "1/2 teaspoon ground ginger" },
  { "id": 659, "recipe_id": 56, "ingredient": "1/4 teaspoon ground cloves" },
  { "id": 660, "recipe_id": 56, "ingredient": "2 large eggs" },
  { "id": 661, "recipe_id": 56, "ingredient": "1 (15 oz) can pumpkin puree" },
  { "id": 662, "recipe_id": 56, "ingredient": "1 (12 fl oz) can evaporated milk" },

  { "id": 663, "recipe_id": 57, "ingredient": "1 (9-inch) unbaked pie crust" },
  { "id": 664, "recipe_id": 57, "ingredient": "1 cup light corn syrup" },
  { "id": 665, "recipe_id": 57, "ingredient": "1 cup packed brown sugar" },
  { "id": 666, "recipe_id": 57, "ingredient": "1/3 cup unsalted butter, melted" },
  { "id": 667, "recipe_id": 57, "ingredient": "3 large eggs" },
  { "id": 668, "recipe_id": 57, "ingredient": "1 1/2 teaspoons vanilla extract" },
  { "id": 669, "recipe_id": 57, "ingredient": "1/4 teaspoon salt" },
  { "id": 670, "recipe_id": 57, "ingredient": "1 1/2 cups pecan halves" },

  { "id": 671, "recipe_id": 52, "ingredient": "12 ounces spaghetti" },
  { "id": 672, "recipe_id": 52, "ingredient": "4 large eggs" },
  { "id": 673, "recipe_id": 52, "ingredient": "1 cup grated Parmesan cheese" },
  { "id": 674, "recipe_id": 52, "ingredient": "4 ounces pancetta or bacon, diced" },
  { "id": 675, "recipe_id": 52, "ingredient": "2 cloves garlic, minced" },
  { "id": 676, "recipe_id": 52, "ingredient": "Salt and freshly ground black pepper, to taste" },
  { "id": 677, "recipe_id": 52, "ingredient": "2 tablespoons chopped fresh parsley (optional)" },

  { "id": 678, "recipe_id": 53, "ingredient": "12 ounces penne pasta" },
  { "id": 679, "recipe_id": 53, "ingredient": "2 tablespoons olive oil" },
  { "id": 680, "recipe_id": 53, "ingredient": "3 cloves garlic, minced" },
  { "id": 681, "recipe_id": 53, "ingredient": "1/2 teaspoon red pepper flakes (adjust to taste)" },
  { "id": 682, "recipe_id": 53, "ingredient": "1 can (14 oz) diced tomatoes" },
  { "id": 683, "recipe_id": 53, "ingredient": "Salt and freshly ground black pepper, to taste" },
  { "id": 684, "recipe_id": 53, "ingredient": "1/4 cup chopped fresh parsley or basil" },
  { "id": 685, "recipe_id": 53, "ingredient": "Grated Parmesan cheese for serving (optional)" },

  { "id": 686, "recipe_id": 54, "ingredient": "9 lasagna noodles" },
  { "id": 687, "recipe_id": 54, "ingredient": "1 pound ground beef" },
  { "id": 688, "recipe_id": 54, "ingredient": "1 small onion, diced" },
  { "id": 689, "recipe_id": 54, "ingredient": "2 cloves garlic, minced" },
  { "id": 690, "recipe_id": 54, "ingredient": "1 (24 oz) jar marinara sauce" },
  { "id": 691, "recipe_id": 54, "ingredient": "1 (15 oz) ricotta cheese" },
  { "id": 692, "recipe_id": 54, "ingredient": "1 large egg" },
  { "id": 693, "recipe_id": 54, "ingredient": "2 cups shredded mozzarella cheese" },
  { "id": 694, "recipe_id": 54, "ingredient": "1/2 cup grated Parmesan cheese" },
  { "id": 695, "recipe_id": 54, "ingredient": "Salt and pepper, to taste" },
  { "id": 696, "recipe_id": 54, "ingredient": "1 teaspoon dried Italian herbs (optional)" },

  { "id": 697, "recipe_id": 44, "ingredient": "1 whole chicken (about 4-5 lbs)" },
  { "id": 698, "recipe_id": 44, "ingredient": "2 tablespoons olive oil or melted butter" },
  { "id": 699, "recipe_id": 44, "ingredient": "1 teaspoon salt" },
  { "id": 700, "recipe_id": 44, "ingredient": "1/2 teaspoon black pepper" },
  { "id": 701, "recipe_id": 44, "ingredient": "1 teaspoon dried thyme or rosemary" },
  { "id": 702, "recipe_id": 44, "ingredient": "1 lemon, halved" },
  { "id": 703, "recipe_id": 44, "ingredient": "4 garlic cloves, smashed" },
  { "id": 704, "recipe_id": 44, "ingredient": "1 onion, quartered (optional)" },

  { "id": 705, "recipe_id": 45, "ingredient": "4 salmon fillets (6 oz each)" },
  { "id": 706, "recipe_id": 45, "ingredient": "2 tablespoons olive oil" },
  { "id": 707, "recipe_id": 45, "ingredient": "1 teaspoon salt" },
  { "id": 708, "recipe_id": 45, "ingredient": "1/2 teaspoon black pepper" },
  { "id": 709, "recipe_id": 45, "ingredient": "1 teaspoon garlic powder" },
  { "id": 710, "recipe_id": 45, "ingredient": "1 teaspoon paprika" },
  { "id": 711, "recipe_id": 45, "ingredient": "1 tablespoon lemon juice" },
  { "id": 712, "recipe_id": 45, "ingredient": "Lemon wedges for serving (optional)" }
]

export const directionsData: Direction[] = [
  { id: 361, recipe_id: 1, instruction: "Combine diced tomatoes, olive oil, and garlic in a bowl." },
  { id: 362, recipe_id: 1, instruction: "Toast bread slices and top with tomato mixture." },
  { id: 363, recipe_id: 1, instruction: "Garnish with basil leaves and serve." },

  { id: 364, recipe_id: 2, instruction: "Preheat oven to 375°F (190°C)." },
  { id: 365, recipe_id: 2, instruction: "Remove stems from mushrooms and fill caps with breadcrumbs and cheese." },
  { id: 366, recipe_id: 2, instruction: "Bake for 15 minutes until golden." },

  { id: 367, recipe_id: 3, instruction: "Skewer tomatoes, mozzarella, and basil onto toothpicks." },
  { id: 368, recipe_id: 3, instruction: "Drizzle with olive oil and balsamic glaze." },
  { id: 369, recipe_id: 3, instruction: "Serve chilled." },


  { id: 370, recipe_id: 4, instruction: "Mix lemon juice, water, and sugar in a pitcher." },
  { id: 371, recipe_id: 4, instruction: "Stir until sugar dissolves." },
  { id: 372, recipe_id: 4, instruction: "Serve over ice with lemon slices." },

  { id: 370, recipe_id: 4, instruction: "Mix lemon juice, water, and sugar in a pitcher." },
  { id: 371, recipe_id: 4, instruction: "Stir until sugar dissolves." },
  { id: 372, recipe_id: 4, instruction: "Serve over ice with lemon slices." },

  { "id": 373, "recipe_id": 11, "instruction": "In a large bowl, sift together the flour, baking powder, salt, and sugar." },
  { "id": 374, "recipe_id": 11, "instruction": "Make a well in the center and pour in the milk, egg, melted butter, and vanilla; mix until smooth." },
  { "id": 375, "recipe_id": 11, "instruction": "Heat a lightly oiled griddle or frying pan over medium-high heat." },
  { "id": 376, "recipe_id": 11, "instruction": "Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake." },
  { "id": 377, "recipe_id": 11, "instruction": "Brown on both sides and serve hot with syrup or desired toppings." },

  { "id": 378, "recipe_id": 13, "instruction": "In a shallow bowl, whisk together eggs, milk, vanilla extract, cinnamon, and salt." },
  { "id": 379, "recipe_id": 13, "instruction": "Heat a skillet over medium heat and melt butter." },
  { "id": 380, "recipe_id": 13, "instruction": "Dip each slice of bread in the egg mixture, coating both sides." },
  { "id": 381, "recipe_id": 13, "instruction": "Place bread slices on the skillet and cook until golden brown on both sides." },
  { "id": 382, "recipe_id": 13, "instruction": "Serve hot with maple syrup or toppings of your choice." },

  { "id": 383, "recipe_id": 16, "instruction": "Toast the bread slices until golden brown." },
  { "id": 384, "recipe_id": 16, "instruction": "Cut the avocado in half, remove the pit, and scoop the flesh into a bowl." },
  { "id": 385, "recipe_id": 16, "instruction": "Mash the avocado with lemon juice, salt, and black pepper." },
  { "id": 386, "recipe_id": 16, "instruction": "Spread the mashed avocado evenly on the toasted bread slices." },
  { "id": 387, "recipe_id": 16, "instruction": "Add optional toppings such as cherry tomatoes, radish slices, microgreens, or a poached egg." },

  { "id": 388, "recipe_id": 17, "instruction": "Toast the English muffins until golden brown." },
  { "id": 389, "recipe_id": 17, "instruction": "Heat a skillet over medium heat and cook the Canadian bacon slices until lightly browned." },
  { "id": 390, "recipe_id": 17, "instruction": "Fill a shallow pan with water, add vinegar, and bring to a gentle simmer. Poach the eggs until whites are set but yolks remain soft (about 3–4 minutes)." },
  { "id": 391, "recipe_id": 17, "instruction": "Place a slice of Canadian bacon on each toasted muffin half." },
  { "id": 392, "recipe_id": 17, "instruction": "Top each muffin half with a poached egg." },
  { "id": 393, "recipe_id": 17, "instruction": "Spoon hollandaise sauce over each egg and garnish with chopped chives or parsley if desired." },

  { "id": 394, "recipe_id": 18, "instruction": "In a bowl, whisk together eggs, milk, salt, and pepper." },
  { "id": 395, "recipe_id": 18, "instruction": "Heat a skillet over medium heat and sauté bell peppers and onions until soft." },
  { "id": 396, "recipe_id": 18, "instruction": "Add the eggs to the skillet and scramble until cooked through." },
  { "id": 397, "recipe_id": 18, "instruction": "Warm the tortillas in a separate pan or microwave." },
  { "id": 398, "recipe_id": 18, "instruction": "Place the scrambled eggs mixture onto each tortilla, top with cooked sausage or bacon and shredded cheese." },
  { "id": 399, "recipe_id": 18, "instruction": "Roll up the tortillas to form burritos and serve with optional toppings like salsa or avocado." },

  { "id": 400, "recipe_id": 21, "instruction": "Preheat the oven to 350°F (175°C) and grease a 9-inch round cake pan." },
  { "id": 401, "recipe_id": 21, "instruction": "In a bowl, cream together 1/2 cup butter and 1 cup sugar until light and fluffy." },
  { "id": 402, "recipe_id": 21, "instruction": "Beat in 2 large eggs, one at a time, then stir in 2 teaspoons vanilla extract." },
  { "id": 403, "recipe_id": 21, "instruction": "In another bowl, combine 1 1/2 cups all-purpose flour, 1 3/4 teaspoons baking powder, and a pinch of salt." },
  { "id": 404, "recipe_id": 21, "instruction": "Gradually add the dry ingredients to the butter mixture, alternating with 1/2 cup milk, mixing until smooth." },
  { "id": 405, "recipe_id": 21, "instruction": "Fold in 1 cup chopped fresh strawberries gently." },
  { "id": 406, "recipe_id": 21, "instruction": "Pour batter into the prepared cake pan and smooth the top." },
  { "id": 407, "recipe_id": 21, "instruction": "Bake for 30-35 minutes, or until a toothpick inserted into the center comes out clean." },
  { "id": 408, "recipe_id": 21, "instruction": "Let the cake cool in the pan for 10 minutes, then turn out onto a wire rack to cool completely." },
  { "id": 409, "recipe_id": 21, "instruction": "Frost with vanilla buttercream and decorate with fresh strawberries before serving." },

  { "id": 410, "recipe_id": 33, "instruction": "Preheat the oven to 350°F (175°C) and grease a 9x9-inch baking pan." },
  { "id": 411, "recipe_id": 33, "instruction": "In a large bowl, cream together 1/2 cup butter and 1 cup sugar until light and fluffy." },
  { "id": 412, "recipe_id": 33, "instruction": "Beat in 2 large eggs, one at a time, then stir in 1 teaspoon vanilla extract." },
  { "id": 413, "recipe_id": 33, "instruction": "In another bowl, combine 1 1/2 cups all-purpose flour, 1 1/2 teaspoons baking powder, and a pinch of salt." },
  { "id": 414, "recipe_id": 33, "instruction": "Gradually add the dry ingredients to the butter mixture, alternating with 1/2 cup milk, mixing until smooth." },
  { "id": 415, "recipe_id": 33, "instruction": "Fold in 2 cups chopped rhubarb gently." },
  { "id": 416, "recipe_id": 33, "instruction": "Pour the batter into the prepared pan and smooth the top." },
  { "id": 417, "recipe_id": 33, "instruction": "Bake for 40-45 minutes, or until a toothpick inserted into the center comes out clean." },
  { "id": 418, "recipe_id": 33, "instruction": "Allow the cake to cool in the pan for 10 minutes, then transfer to a wire rack to cool completely." },
  { "id": 419, "recipe_id": 33, "instruction": "Optional: dust the cooled cake with powdered sugar before serving." },

  { "id": 420, "recipe_id": 77, "instruction": "Preheat the oven to 350°F (175°C). Grease and line a 9-inch round cake pan." },
  { "id": 421, "recipe_id": 77, "instruction": "In a bowl, sift together 1 1/2 cups all-purpose flour, 1 cup sugar, 1/2 cup cocoa powder, 1 1/2 teaspoons baking soda, and 1/2 teaspoon salt." },
  { "id": 422, "recipe_id": 77, "instruction": "In another bowl, whisk together 1 cup stout beer, 1/2 cup vegetable oil, 2 eggs, and 1 teaspoon vanilla extract." },
  { "id": 423, "recipe_id": 77, "instruction": "Gradually mix the wet ingredients into the dry ingredients until smooth." },
  { "id": 424, "recipe_id": 77, "instruction": "Pour the batter into the prepared cake pan." },
  { "id": 425, "recipe_id": 77, "instruction": "Bake for 40-45 minutes, or until a toothpick inserted in the center comes out clean." },
  { "id": 426, "recipe_id": 77, "instruction": "Allow the cake to cool in the pan for 10 minutes, then transfer to a wire rack to cool completely." },
  { "id": 427, "recipe_id": 77, "instruction": "Optional: frost with chocolate ganache or your favorite icing before serving." },

  { "id": 428, "recipe_id": 19, "instruction": "Line a baking sheet with parchment paper and set aside." },
  { "id": 429, "recipe_id": 19, "instruction": "In a medium saucepan, combine brown sugar, heavy cream, and butter." },
  { "id": 430, "recipe_id": 19, "instruction": "Cook over medium heat, stirring constantly, until the mixture reaches 234°F (soft-ball stage) on a candy thermometer." },
  { "id": 431, "recipe_id": 19, "instruction": "Remove from heat and stir in vanilla extract, salt, and pecans." },
  { "id": 432, "recipe_id": 19, "instruction": "Continue stirring until the mixture thickens slightly and loses its gloss." },
  { "id": 433, "recipe_id": 19, "instruction": "Drop spoonfuls of the mixture onto the prepared baking sheet." },
  { "id": 434, "recipe_id": 19, "instruction": "Allow pralines to cool and harden at room temperature before serving." },

  { "id": 435, "recipe_id": 22, "instruction": "Place mint leaves and 1 lime wedge into a sturdy glass." },
  { "id": 436, "recipe_id": 22, "instruction": "Use a muddler to crush the mint and lime to release the mint oils and lime juice." },
  { "id": 437, "recipe_id": 22, "instruction": "Add 2 more lime wedges and the sugar, and muddle again to release the lime juice." },
  { "id": 438, "recipe_id": 22, "instruction": "Fill the glass almost to the top with ice cubes." },
  { "id": 439, "recipe_id": 22, "instruction": "Pour the rum over the ice, and fill the glass with club soda." },
  { "id": 440, "recipe_id": 22, "instruction": "Stir well and garnish with the remaining lime wedge and a sprig of mint." },

  { "id": 441, "recipe_id": 32, "instruction": "In a pitcher, combine 1 cup fresh lemon juice, 1/2 cup simple syrup, and 1/2 cup raspberries." },
  { "id": 442, "recipe_id": 32, "instruction": "Use a muddler or spoon to gently crush the raspberries to release their juice." },
  { "id": 443, "recipe_id": 32, "instruction": "Add 2 cups cold water and stir to combine." },
  { "id": 444, "recipe_id": 32, "instruction": "Add 1 cup vodka and stir gently." },
  { "id": 445, "recipe_id": 32, "instruction": "Fill glasses with ice and pour the raspberry vodka lemonade over the ice." },
  { "id": 446, "recipe_id": 32, "instruction": "Garnish with fresh raspberries and lemon slices before serving." },

  { "id": 447, "recipe_id": 41, "instruction": "Preheat your espresso machine and portafilter." },
  { "id": 448, "recipe_id": 41, "instruction": "Measure 18-20 grams of finely ground coffee and fill the portafilter." },
  { "id": 449, "recipe_id": 41, "instruction": "Tamp the coffee evenly and firmly." },
  { "id": 450, "recipe_id": 41, "instruction": "Lock the portafilter into the espresso machine." },
  { "id": 451, "recipe_id": 41, "instruction": "Start the extraction and brew 2 ounces of espresso over 25-30 seconds." },
  { "id": 452, "recipe_id": 41, "instruction": "Serve immediately in a pre-warmed espresso cup." },

  { "id": 453, "recipe_id": 76, "instruction": "Combine all the spices in a small bowl." },
  { "id": 454, "recipe_id": 76, "instruction": "Mix thoroughly until evenly blended." },
  { "id": 455, "recipe_id": 76, "instruction": "Store in an airtight container in a cool, dry place." },
  { "id": 456, "recipe_id": 76, "instruction": "Use as needed in recipes requiring curry powder." },

  { "id": 457, "recipe_id": 78, "instruction": "Preheat oven to 375°F (190°C) and lightly grease a baking dish." },
  { "id": 458, "recipe_id": 78, "instruction": "In a skillet over medium heat, sauté onion and garlic until soft." },
  { "id": 459, "recipe_id": 78, "instruction": "Add ground beef or turkey and cook until browned. Drain excess fat." },
  { "id": 460, "recipe_id": 78, "instruction": "Stir in cooked rice or quinoa, marinara sauce, and Italian herbs. Season with salt and pepper." },
  { "id": 461, "recipe_id": 78, "instruction": "Spoon the mixture evenly into the hollowed zucchini halves." },
  { "id": 462, "recipe_id": 78, "instruction": "Top each zucchini boat with shredded mozzarella and Parmesan cheese." },
  { "id": 463, "recipe_id": 78, "instruction": "Bake for 20-25 minutes, until the zucchini is tender and cheese is melted and bubbly." },
  { "id": 464, "recipe_id": 78, "instruction": "Serve hot, garnished with fresh basil or parsley if desired." },

  { "id": 465, "recipe_id": 75, "instruction": "Heat olive oil in a large pot over medium heat." },
  { "id": 466, "recipe_id": 75, "instruction": "Add onion and garlic, sauté until translucent." },
  { "id": 467, "recipe_id": 75, "instruction": "Add carrots and celery, cook for 5 minutes until slightly softened." },
  { "id": 468, "recipe_id": 75, "instruction": "Add zucchini, diced tomatoes, broth, beans, and Italian herbs." },
  { "id": 469, "recipe_id": 75, "instruction": "Season with salt and pepper and bring to a boil." },
  { "id": 470, "recipe_id": 75, "instruction": "Reduce heat and simmer for 15 minutes." },
  { "id": 471, "recipe_id": 75, "instruction": "Add pasta and cook until tender, about 8-10 minutes." },
  { "id": 472, "recipe_id": 75, "instruction": "Serve hot, garnished with grated Parmesan and fresh parsley." },

  { "id": 473, "recipe_id": 70, "instruction": "Preheat oven to 375°F (190°C)." },
  { "id": 474, "recipe_id": 70, "instruction": "Spread tortilla chips evenly on a baking sheet or oven-safe dish." },
  { "id": 475, "recipe_id": 70, "instruction": "Sprinkle shredded cheese over the chips." },
  { "id": 476, "recipe_id": 70, "instruction": "Add cooked ground beef or chicken, if using, along with diced tomatoes, jalapeños, olives, and onions." },
  { "id": 477, "recipe_id": 70, "instruction": "Bake for 10-12 minutes, or until the cheese is melted and bubbly." },
  { "id": 478, "recipe_id": 70, "instruction": "Serve immediately with sour cream, guacamole, and salsa." },

  { "id": 479, "recipe_id": 27, "instruction": "Preheat the oven to 375°F (190°C) and lightly grease a 9-inch pie dish." },
  { "id": 480, "recipe_id": 27, "instruction": "Slice 2 medium zucchinis and sauté them in a skillet with 1 tablespoon olive oil until softened." },
  { "id": 481, "recipe_id": 27, "instruction": "In a bowl, whisk together 4 large eggs, 1 cup milk, 1/2 cup shredded cheese, salt, and pepper." },
  { "id": 482, "recipe_id": 27, "instruction": "Place a pre-made or homemade pie crust in the greased pie dish." },
  { "id": 483, "recipe_id": 27, "instruction": "Spread the sautéed zucchini evenly over the pie crust." },
  { "id": 484, "recipe_id": 27, "instruction": "Pour the egg and cheese mixture over the zucchini." },
  { "id": 485, "recipe_id": 27, "instruction": "Bake for 35-40 minutes, or until the quiche is set and the top is golden brown." },
  { "id": 486, "recipe_id": 27, "instruction": "Allow the quiche to cool for 10 minutes before slicing and serving." },

  { "id": 487, "recipe_id": 69, "instruction": "In a large bowl, combine shredded cabbage and carrots." },
  { "id": 488, "recipe_id": 69, "instruction": "In a separate small bowl, whisk together mayonnaise, apple cider vinegar, sugar, salt, and pepper." },
  { "id": 489, "recipe_id": 69, "instruction": "Pour the dressing over the cabbage and carrots." },
  { "id": 490, "recipe_id": 69, "instruction": "Toss well to coat evenly." },
  { "id": 491, "recipe_id": 69, "instruction": "Cover and refrigerate for at least 1 hour before serving to allow flavors to meld." },

  { "id": 492, "recipe_id": 38, "instruction": "Toast 1/4 cup pine nuts in a dry skillet over medium heat until lightly golden." },
  { "id": 493, "recipe_id": 38, "instruction": "In a food processor, combine 1 cup fresh dill, toasted pine nuts, 1/2 cup grated Parmesan cheese, and 2 cloves garlic." },
  { "id": 494, "recipe_id": 38, "instruction": "Pulse until the ingredients are finely chopped." },
  { "id": 495, "recipe_id": 38, "instruction": "With the processor running, slowly add 1/2 cup olive oil until the mixture forms a smooth paste." },
  { "id": 496, "recipe_id": 38, "instruction": "Season with salt and pepper to taste." },
  { "id": 497, "recipe_id": 38, "instruction": "Use immediately or store in an airtight container in the refrigerator for up to one week." },

  { "id": 498, "recipe_id": 46, "instruction": "Preheat the oven to 375°F (190°C)." },
  { "id": 499, "recipe_id": 46, "instruction": "Cut a slit lengthwise in each hot dog, being careful not to cut all the way through." },
  { "id": 500, "recipe_id": 46, "instruction": "Stuff each slit with shredded cheese." },
  { "id": 501, "recipe_id": 46, "instruction": "Place the hot dogs on a baking sheet lined with parchment paper." },
  { "id": 502, "recipe_id": 46, "instruction": "Bake for 10-15 minutes, or until the cheese is melted and the hot dogs are heated through." },
  { "id": 503, "recipe_id": 46, "instruction": "Serve in buns with your favorite toppings, such as ketchup, mustard, or relish." },

  { "id": 504, "recipe_id": 62, "instruction": "Heat a skillet over medium heat." },
  { "id": 505, "recipe_id": 62, "instruction": "Butter one side of each slice of bread." },
  { "id": 506, "recipe_id": 62, "instruction": "Place one slice of bread, buttered side down, on the skillet." },
  { "id": 507, "recipe_id": 62, "instruction": "Top with 2 slices of cheese, then place the second slice of bread on top, buttered side up." },
  { "id": 508, "recipe_id": 62, "instruction": "Cook until the bottom slice is golden brown, about 2-3 minutes." },
  { "id": 509, "recipe_id": 62, "instruction": "Flip the sandwich and cook until the other side is golden and the cheese is melted." },
  { "id": 510, "recipe_id": 62, "instruction": "Remove from the skillet, slice, and serve immediately." },

  { "id": 511, "recipe_id": 35, "instruction": "In a medium bowl, combine 1/2 cup mayonnaise, 2 tablespoons ketchup, and 1 tablespoon sweet pickle relish." },
  { "id": 512, "recipe_id": 35, "instruction": "Add 1 teaspoon white vinegar, 1/2 teaspoon sugar, and a pinch of salt and pepper." },
  { "id": 513, "recipe_id": 35, "instruction": "Whisk all ingredients together until smooth and well combined." },
  { "id": 514, "recipe_id": 35, "instruction": "Taste and adjust seasoning, adding more vinegar or sugar if desired." },
  { "id": 515, "recipe_id": 35, "instruction": "Cover and refrigerate for at least 30 minutes before serving to allow flavors to meld." },

  { "id": 516, "recipe_id": 36, "instruction": "In a medium bowl, whisk together the egg, Dijon mustard, white wine vinegar, and salt." },
  { "id": 517, "recipe_id": 36, "instruction": "While whisking constantly, slowly drizzle in the oil, starting with just a few drops at a time." },
  { "id": 518, "recipe_id": 36, "instruction": "As the mixture begins to emulsify and thicken, you can increase the oil flow to a thin stream." },
  { "id": 519, "recipe_id": 36, "instruction": "Once all the oil is incorporated and the mayonnaise is thick and smooth, whisk in the lemon juice." },
  { "id": 520, "recipe_id": 36, "instruction": "Taste and adjust seasoning with additional salt or lemon juice if desired." },
  { "id": 521, "recipe_id": 36, "instruction": "Transfer the mayonnaise to a clean jar or container and refrigerate." },
  { "id": 522, "recipe_id": 36, "instruction": "Use within 1 week." },

  { "id": 523, "recipe_id": 51, "instruction": "Preheat the oven to 425°F (220°C) and prepare a 9-inch pie dish with a pie crust." },
  { "id": 524, "recipe_id": 51, "instruction": "Peel, pit, and slice 6-7 ripe peaches." },
  { "id": 525, "recipe_id": 51, "instruction": "In a large bowl, combine the peach slices with 3/4 cup sugar, 1/4 cup all-purpose flour, 1/4 teaspoon ground cinnamon, and a pinch of salt." },
  { "id": 526, "recipe_id": 51, "instruction": "Pour the peach mixture into the prepared pie crust." },
  { "id": 527, "recipe_id": 51, "instruction": "Dot the filling with 2 tablespoons butter." },
  { "id": 528, "recipe_id": 51, "instruction": "Cover with the top crust, crimp the edges, and cut small slits for steam to escape." },
  { "id": 529, "recipe_id": 51, "instruction": "Brush the top crust with a little milk and sprinkle with sugar for a golden finish." },
  { "id": 530, "recipe_id": 51, "instruction": "Bake for 45-50 minutes until the crust is golden and the filling is bubbly." },
  { "id": 531, "recipe_id": 51, "instruction": "Allow the pie to cool for at least 2 hours before serving to let the filling set." },

  { "id": 532, "recipe_id": 55, "instruction": "In a large bowl, combine flour and salt. Cut in chilled butter until the mixture resembles coarse crumbs." },
  { "id": 533, "recipe_id": 55, "instruction": "Gradually add ice water, 1 tablespoon at a time, until the dough comes together." },
  { "id": 534, "recipe_id": 55, "instruction": "Divide dough in half, shape into disks, wrap in plastic wrap, and refrigerate for at least 1 hour." },
  { "id": 535, "recipe_id": 55, "instruction": "Preheat oven to 425°F (220°C)." },
  { "id": 536, "recipe_id": 55, "instruction": "Roll out one disk of dough to fit a 9-inch pie dish and place it in the dish." },
  { "id": 537, "recipe_id": 55, "instruction": "In a large bowl, toss apple slices with granulated sugar, brown sugar, cinnamon, nutmeg, salt, and lemon juice." },
  { "id": 538, "recipe_id": 55, "instruction": "Pour apple mixture into the prepared pie crust and dot with 1 tablespoon butter." },
  { "id": 539, "recipe_id": 55, "instruction": "Roll out second disk of dough and place over the apples. Trim, seal, and crimp edges." },
  { "id": 540, "recipe_id": 55, "instruction": "Cut small slits in the top crust for steam to escape." },
  { "id": 541, "recipe_id": 55, "instruction": "Brush the top crust with beaten egg and sprinkle with coarse sugar if desired." },
  { "id": 542, "recipe_id": 55, "instruction": "Bake for 45-50 minutes, until the crust is golden and filling is bubbly. Cover edges with foil if browning too quickly." },
  { "id": 543, "recipe_id": 55, "instruction": "Cool the pie for at least 2 hours before serving to allow the filling to set." },

  { "id": 544, "recipe_id": 56, "instruction": "Preheat the oven to 425°F (220°C)." },
  { "id": 545, "recipe_id": 56, "instruction": "In a large bowl, whisk together sugar, salt, cinnamon, ginger, and cloves." },
  { "id": 546, "recipe_id": 56, "instruction": "Beat in eggs, then stir in pumpkin puree and evaporated milk until smooth." },
  { "id": 547, "recipe_id": 56, "instruction": "Pour the filling into the unbaked pie crust." },
  { "id": 548, "recipe_id": 56, "instruction": "Bake for 15 minutes at 425°F (220°C)." },
  { "id": 549, "recipe_id": 56, "instruction": "Reduce the oven temperature to 350°F (175°C) and continue baking for 40-50 minutes, or until a knife inserted near the center comes out clean." },
  { "id": 550, "recipe_id": 56, "instruction": "Cool on a wire rack for 2 hours. Serve at room temperature or chilled." },

  { "id": 551, "recipe_id": 57, "instruction": "Preheat the oven to 350°F (175°C)." },
  { "id": 552, "recipe_id": 57, "instruction": "In a large bowl, whisk together corn syrup, brown sugar, melted butter, eggs, vanilla, and salt until smooth." },
  { "id": 553, "recipe_id": 57, "instruction": "Arrange pecan halves evenly in the unbaked pie crust." },
  { "id": 554, "recipe_id": 57, "instruction": "Pour the filling over the pecans." },
  { "id": 555, "recipe_id": 57, "instruction": "Bake for 50-60 minutes, until the filling is set and lightly browned. Cover the edges of the crust with foil if browning too quickly." },
  { "id": 556, "recipe_id": 57, "instruction": "Cool the pie completely on a wire rack before serving." },

  { "id": 557, "recipe_id": 61, "instruction": "Preheat oven to 375°F (190°C) and place a pie crust in a 9-inch pie dish." },
  { "id": 558, "recipe_id": 61, "instruction": "In a large bowl, combine 1 1/2 cups sliced peaches, 3/4 cup sugar, 2 tablespoons flour, and 1/4 teaspoon salt." },
  { "id": 559, "recipe_id": 61, "instruction": "In a separate bowl, whisk together 1 cup sour cream and 2 eggs until smooth." },
  { "id": 560, "recipe_id": 61, "instruction": "Gently fold the sour cream mixture into the peach mixture." },
  { "id": 561, "recipe_id": 61, "instruction": "Pour the filling into the prepared pie crust." },
  { "id": 562, "recipe_id": 61, "instruction": "Bake for 40-45 minutes, or until the filling is set and lightly golden." },
  { "id": 563, "recipe_id": 61, "instruction": "Allow the pie to cool to room temperature before serving. Chill if desired." },

  { "id": 564, "recipe_id": 63, "instruction": "Prepare a 9-inch pre-baked pie crust and let it cool completely." },
  { "id": 565, "recipe_id": 63, "instruction": "In a medium bowl, combine 2 cups fresh strawberries with 1/2 cup sugar and let sit for 10 minutes." },
  { "id": 566, "recipe_id": 63, "instruction": "In a separate bowl, whip 1 cup heavy cream with 1 teaspoon vanilla extract until stiff peaks form." },
  { "id": 567, "recipe_id": 63, "instruction": "Fold the macerated strawberries gently into the whipped cream." },
  { "id": 568, "recipe_id": 63, "instruction": "Pour the mixture into the cooled pie crust and spread evenly." },
  { "id": 569, "recipe_id": 63, "instruction": "Freeze the pie for at least 4 hours, or until firm." },
  { "id": 570, "recipe_id": 63, "instruction": "Before serving, let the pie sit at room temperature for 10-15 minutes for easier slicing." },

  { "id": 571, "recipe_id": 64, "instruction": "Pre-bake a 9-inch pie crust and allow it to cool completely." },
  { "id": 572, "recipe_id": 64, "instruction": "In a medium saucepan, combine 1 can (20 oz) crushed pineapple with juice, 3/4 cup sugar, and 3 tablespoons cornstarch." },
  { "id": 573, "recipe_id": 64, "instruction": "Cook over medium heat, stirring constantly, until mixture thickens and comes to a boil." },
  { "id": 574, "recipe_id": 64, "instruction": "Remove from heat and let cool slightly." },
  { "id": 575, "recipe_id": 64, "instruction": "In a bowl, whip 1 cup heavy cream with 1 teaspoon vanilla extract until stiff peaks form." },
  { "id": 576, "recipe_id": 64, "instruction": "Gently fold the whipped cream into the cooled pineapple mixture." },
  { "id": 577, "recipe_id": 64, "instruction": "Pour the filling into the pre-baked pie crust and smooth the top." },
  { "id": 578, "recipe_id": 64, "instruction": "Chill the pie in the refrigerator for at least 4 hours before serving." },

  { "id": 579, "recipe_id": 24, "instruction": "Cook 12 ounces of penne pasta according to package instructions. Drain and rinse with cold water." },
  { "id": 580, "recipe_id": 24, "instruction": "In a large bowl, combine the cooked pasta, 1 cup cherry tomatoes (halved), 1/2 cup diced cucumber, 1/4 cup sliced red onion, 1/4 cup kalamata olives, and 1/2 cup feta cheese crumbles." },
  { "id": 581, "recipe_id": 24, "instruction": "In a small bowl, whisk together 1/4 cup olive oil, 2 tablespoons red wine vinegar, 1 teaspoon dried oregano, salt, and pepper." },
  { "id": 582, "recipe_id": 24, "instruction": "Pour the dressing over the pasta mixture and toss gently to coat evenly." },
  { "id": 583, "recipe_id": 24, "instruction": "Chill in the refrigerator for at least 30 minutes before serving." },
  { "id": 584, "recipe_id": 24, "instruction": "Garnish with extra feta and fresh oregano, if desired." },

  { "id": 585, "recipe_id": 52, "instruction": "Cook spaghetti according to package directions until al dente. Reserve 1 cup of pasta water and drain the rest." },
  { "id": 586, "recipe_id": 52, "instruction": "In a bowl, whisk together eggs and Parmesan cheese. Set aside." },
  { "id": 587, "recipe_id": 52, "instruction": "In a large skillet over medium heat, cook pancetta or bacon until crispy. Add garlic and sauté for 1 minute." },
  { "id": 588, "recipe_id": 52, "instruction": "Add the hot cooked pasta to the skillet and toss to combine with pancetta." },
  { "id": 589, "recipe_id": 52, "instruction": "Remove the skillet from heat and quickly pour in the egg and cheese mixture, tossing rapidly to create a creamy sauce. Add reserved pasta water a little at a time as needed to reach desired consistency." },
  { "id": 590, "recipe_id": 52, "instruction": "Season with salt and freshly ground black pepper to taste." },
  { "id": 591, "recipe_id": 52, "instruction": "Garnish with chopped parsley if desired and serve immediately." },

  { "id": 592, "recipe_id": 53, "instruction": "Cook penne pasta according to package instructions until al dente. Drain and set aside." },
  { "id": 593, "recipe_id": 53, "instruction": "In a large skillet, heat olive oil over medium heat. Add minced garlic and red pepper flakes and sauté for 1-2 minutes until fragrant." },
  { "id": 594, "recipe_id": 53, "instruction": "Add diced tomatoes (with juice), salt, and black pepper. Simmer for 10-12 minutes, stirring occasionally." },
  { "id": 595, "recipe_id": 53, "instruction": "Add the cooked penne pasta to the skillet and toss to coat evenly with the sauce." },
  { "id": 596, "recipe_id": 53, "instruction": "Remove from heat and stir in chopped parsley or basil." },
  { "id": 597, "recipe_id": 53, "instruction": "Serve hot with grated Parmesan cheese if desired." },

  { "id": 598, "recipe_id": 54, "instruction": "Preheat oven to 375°F (190°C)." },
  { "id": 599, "recipe_id": 54, "instruction": "Cook lasagna noodles according to package instructions. Drain and set aside." },
  { "id": 600, "recipe_id": 54, "instruction": "In a large skillet, cook ground beef, diced onion, and minced garlic over medium heat until beef is browned. Drain excess fat." },
  { "id": 601, "recipe_id": 54, "instruction": "Stir in marinara sauce and Italian herbs. Simmer for 5-10 minutes. Season with salt and pepper to taste." },
  { "id": 602, "recipe_id": 54, "instruction": "In a bowl, combine ricotta cheese with the egg, a pinch of salt, and pepper." },
  { "id": 603, "recipe_id": 54, "instruction": "Spread a thin layer of meat sauce on the bottom of a 9x13-inch baking dish." },
  { "id": 604, "recipe_id": 54, "instruction": "Layer 3 noodles over the sauce, then spread half of the ricotta mixture, half of the mozzarella, and one-third of the remaining meat sauce." },
  { "id": 605, "recipe_id": 54, "instruction": "Repeat layers with remaining noodles, ricotta, mozzarella, and meat sauce. Top with remaining mozzarella and Parmesan cheese." },
  { "id": 606, "recipe_id": 54, "instruction": "Cover with foil and bake for 25 minutes. Remove foil and bake an additional 20 minutes until cheese is golden and bubbly." },
  { "id": 607, "recipe_id": 54, "instruction": "Let lasagna rest for 10 minutes before slicing and serving." },

  { "id": 608, "recipe_id": 23, "instruction": "Preheat oven to 400°F (200°C) and lightly grease a baking dish." },
  { "id": 609, "recipe_id": 23, "instruction": "Season 4 chicken breasts with salt and pepper on both sides." },
  { "id": 610, "recipe_id": 23, "instruction": "In a small saucepan, combine 1/2 cup plum preserves, 1-2 minced habanero peppers (adjust to taste), 2 tablespoons soy sauce, and 1 tablespoon apple cider vinegar. Heat over medium until smooth." },
  { "id": 611, "recipe_id": 23, "instruction": "Place chicken breasts in the prepared baking dish and brush generously with the plum habanero sauce." },
  { "id": 612, "recipe_id": 23, "instruction": "Bake for 25-30 minutes, or until the chicken is cooked through (internal temperature 165°F / 74°C), basting with additional sauce halfway through." },
  { "id": 613, "recipe_id": 23, "instruction": "Remove from oven and let rest for 5 minutes before serving." },
  { "id": 614, "recipe_id": 23, "instruction": "Serve chicken with extra plum habanero sauce drizzled on top." },

  { "id": 615, "recipe_id": 44, "instruction": "Preheat oven to 425°F (220°C)." },
  { "id": 616, "recipe_id": 44, "instruction": "Remove giblets from the chicken cavity and pat the chicken dry with paper towels." },
  { "id": 617, "recipe_id": 44, "instruction": "Rub the chicken all over with olive oil or melted butter, then season with salt, pepper, and dried herbs." },
  { "id": 618, "recipe_id": 44, "instruction": "Stuff the cavity with lemon halves, garlic cloves, and onion if using." },
  { "id": 619, "recipe_id": 44, "instruction": "Place the chicken breast-side up on a roasting rack in a baking dish." },
  { "id": 620, "recipe_id": 44, "instruction": "Roast in the preheated oven for 1 hour 15 minutes to 1 hour 30 minutes, or until internal temperature reaches 165°F (74°C) in the thickest part of the thigh." },
  { "id": 621, "recipe_id": 44, "instruction": "Baste the chicken occasionally with pan juices for extra flavor and moisture." },
  { "id": 622, "recipe_id": 44, "instruction": "Remove from oven and let rest for 10-15 minutes before carving and serving." },

  { "id": 623, "recipe_id": 45, "instruction": "Preheat the grill to medium-high heat and lightly oil the grates." },
  { "id": 624, "recipe_id": 45, "instruction": "Brush salmon fillets with olive oil and season with salt, pepper, garlic powder, and paprika." },
  { "id": 625, "recipe_id": 45, "instruction": "Place salmon skin-side down on the grill." },
  { "id": 626, "recipe_id": 45, "instruction": "Grill for 4-6 minutes per side, depending on thickness, until the salmon is cooked through and flakes easily with a fork." },
  { "id": 627, "recipe_id": 45, "instruction": "Drizzle with lemon juice before serving." },
  { "id": 628, "recipe_id": 45, "instruction": "Serve with lemon wedges if desired." }


]

export const nutritionData: Nutrition[] = [
  { recipe_id: 1 },
  { id: 1, recipe_id: 2, calories: "589 kcal", fat: "38", saturated_fat: "11", unsaturated_fat: "0", carbs: "17", fiber: "1", sugar: "0", cholesterol: "175", protein: "43", sodium: "1748" },
  { recipe_id: 3 },
  { id: 2, recipe_id: 4, calories: "423 kcal", fat: "19", saturated_fat: "6", unsaturated_fat: "0", carbs: "57", fiber: "4", sugar: "8", cholesterol: "75", protein: "10", sodium: "457" },
  { id: 3, recipe_id: 5, calories: "252 kcal", fat: "16", saturated_fat: "4", unsaturated_fat: "0", carbs: "22", fiber: "2", sugar: "3", cholesterol: "91", protein: "6", sodium: "307" },
  { id: 4, recipe_id: 6, calories: "209 kcal", fat: "1", saturated_fat: "0", unsaturated_fat: "0", carbs: "48", fiber: "2", sugar: "30", cholesterol: "2", protein: "3", sodium: "269" },
  { id: 5, recipe_id: 7, calories: "108 kcal", fat: "0", saturated_fat: "0", unsaturated_fat: "0", carbs: "29", fiber: "1", sugar: "26", cholesterol: "0", protein: "0", sodium: "8" },
  { id: 6, recipe_id: 8, calories: "261 kcal", fat: "16", saturated_fat: "8", unsaturated_fat: "0", carbs: "30", fiber: "2", sugar: "21", cholesterol: "51", protein: "3", sodium: "166" },
  { id: 7, recipe_id: 9, calories: "113 kcal", fat: "9", saturated_fat: "1", unsaturated_fat: "0", carbs: "8", fiber: "2", sugar: "3", cholesterol: "0", protein: "2", sodium: "203" },
  { id: 8, recipe_id: 10, calories: "150 kcal", fat: "14", saturated_fat: "9", unsaturated_fat: "0", carbs: "7", fiber: "0", sugar: "0", cholesterol: "40", protein: "1", sodium: "19" },
  { id: 9, recipe_id: 12, calories: "215 kcal", fat: "13", saturated_fat: "8", unsaturated_fat: "0", carbs: "25", fiber: "0", sugar: "25", cholesterol: "41", protein: "0", sodium: "97" },
  { id: 10, recipe_id: 14, calories: "81 kcal", fat: "0", saturated_fat: "0", unsaturated_fat: "0", carbs: "21", fiber: "1", sugar: "12", cholesterol: "0", protein: "0", sodium: "6" },
  { id: 11, recipe_id: 15, calories: "292 kcal", fat: "9", saturated_fat: "6", unsaturated_fat: "0", carbs: "33", fiber: "3", sugar: "5", cholesterol: "36", protein: "19", sodium: "367" },
  { id: 12, recipe_id: 19, calories: "166 kcal", fat: "7", saturated_fat: "3", unsaturated_fat: "0", carbs: "27", fiber: "0", sugar: "23", cholesterol: "12", protein: "2", sodium: "74" },
  { id: 13, recipe_id: 20, calories: "77 kcal", fat: "4", saturated_fat: "2", unsaturated_fat: "0", carbs: "9", fiber: "0", sugar: "0", cholesterol: "17", protein: "1", sodium: "79" },
  { id: 14, recipe_id: 21, calories: "487 kcal", fat: "28", saturated_fat: "12", unsaturated_fat: "0", carbs: "57", fiber: "0", sugar: "0", cholesterol: "83", protein: "3", sodium: "280" },
  { id: 15, recipe_id: 23, calories: "660 kcal", fat: "8", saturated_fat: "2", unsaturated_fat: "0", carbs: "99", fiber: "4", sugar: "21", cholesterol: "99", protein: "48", sodium: "115" },
  { id: 16, recipe_id: 24, calories: "375 kcal", fat: "17", saturated_fat: "3", unsaturated_fat: "0", carbs: "49", fiber: "4", sugar: "0", cholesterol: "1", protein: "9", sodium: "429" },
  { id: 17, recipe_id: 25, calories: "89 kcal", fat: "4", saturated_fat: "1", unsaturated_fat: "0", carbs: "14", fiber: "2", sugar: "0", cholesterol: "0", protein: "1", sodium: "126" },
  { id: 18, recipe_id: 26, calories: "276 kcal", fat: "10", saturated_fat: "1", unsaturated_fat: "0", carbs: "43", fiber: "2", sugar: "0", cholesterol: "0", protein: "4", sodium: "670" },
  { id: 19, recipe_id: 27, calories: "268 kcal", fat: "20", saturated_fat: "5", unsaturated_fat: "0", carbs: "16", fiber: "1", sugar: "2", cholesterol: "128", protein: "8", sodium: "692" },
  { id: 20, recipe_id: 28, calories: "260 kcal", fat: "16", saturated_fat: "9", unsaturated_fat: "0", carbs: "26", fiber: "1", sugar: "20", cholesterol: "89", protein: "4", sodium: "160" },
  { id: 21, recipe_id: 29, calories: "537 kcal", fat: "36", saturated_fat: "22", unsaturated_fat: "0", carbs: "51", fiber: "3", sugar: "31", cholesterol: "221", protein: "6", sodium: "293" },
  { id: 22, recipe_id: 30, calories: "513 kcal", fat: "7", saturated_fat: "4", unsaturated_fat: "0", carbs: "111", fiber: "3", sugar: "84", cholesterol: "18", protein: "5", sodium: "372" },
  { id: 23, recipe_id: 31, calories: "540 kcal", fat: "30", saturated_fat: "17", unsaturated_fat: "0", carbs: "30", fiber: "3", sugar: "6", cholesterol: "314", protein: "32", sodium: "1148" },
  { id: 24, recipe_id: 32, calories: "224 kcal", fat: "0", saturated_fat: "0", unsaturated_fat: "0", carbs: "32", fiber: "1", sugar: "0", cholesterol: "0", protein: "0", sodium: "17" },
  { id: 25, recipe_id: 33, calories: "386 kcal", fat: "14", saturated_fat: "6", unsaturated_fat: "0", carbs: "60", fiber: "1", sugar: "0", cholesterol: "68", protein: "6", sodium: "300" },
  { id: 26, recipe_id: 34, calories: "262 kcal", fat: "0", saturated_fat: "0", unsaturated_fat: "0", carbs: "69", fiber: "2", sugar: "0", cholesterol: "0", protein: "1", sodium: "9" },
  { id: 27, recipe_id: 35, calories: "69 kcal", fat: "7", saturated_fat: "1", unsaturated_fat: "0", carbs: "2", fiber: "0", sugar: "1", cholesterol: "4", protein: "0", sodium: "134" },
  { id: 28, recipe_id: 37, calories: "83 kcal", fat: "1", saturated_fat: "1", unsaturated_fat: "0", carbs: "17", fiber: "2", sugar: "0", cholesterol: "4", protein: "3", sodium: "788" },
  { id: 29, recipe_id: 38, calories: "165 kcal", fat: "16", saturated_fat: "3", unsaturated_fat: "0", carbs: "3", fiber: "1", sugar: "0", cholesterol: "4", protein: "4", sodium: "143" },
  { id: 30, recipe_id: 39, calories: "117 kcal", fat: "8", saturated_fat: "1", unsaturated_fat: "0", carbs: "10", fiber: "2", sugar: "3", cholesterol: "4", protein: "2", sodium: "158" },
  { id: 31, recipe_id: 40, calories: "334 kcal", fat: "8", saturated_fat: "1", unsaturated_fat: "0", carbs: "55", fiber: "4", sugar: "3", cholesterol: "93", protein: "10", sodium: "162" },
  { id: 32, recipe_id: 42, calories: "176 kcal", fat: "8", saturated_fat: "3", unsaturated_fat: "0", carbs: "24", fiber: "1", sugar: "0", cholesterol: "86", protein: "4", sodium: "114" },
  { id: 33, recipe_id: 43, calories: "606 kcal", fat: "35", saturated_fat: "14", unsaturated_fat: "0", carbs: "7", fiber: "1", sugar: "0", cholesterol: "194", protein: "64", sodium: "1775" },
  { id: 34, recipe_id: 46, calories: "546 kcal", fat: "38", saturated_fat: "19", unsaturated_fat: "0", carbs: "32", fiber: "1", sugar: "5", cholesterol: "88", protein: "19", sodium: "1068" },
  { id: 35, recipe_id: 47, calories: "211 kcal", fat: "12", saturated_fat: "3", unsaturated_fat: "0", carbs: "23", fiber: "6", sugar: "2", cholesterol: "5", protein: "6", sodium: "394" },
  { id: 36, recipe_id: 48, calories: "473 kcal", fat: "26", saturated_fat: "12", unsaturated_fat: "0", carbs: "28", fiber: "3", sugar: "4", cholesterol: "101", protein: "31", sodium: "1282" },
  { id: 37, recipe_id: 49, calories: "151 kcal", fat: "4", saturated_fat: "3", unsaturated_fat: "0", carbs: "28", fiber: "1", sugar: "25", cholesterol: "8", protein: "1", sodium: "1176" },
  { id: 38, recipe_id: 50, calories: "327 kcal", fat: "17", saturated_fat: "6", unsaturated_fat: "0", carbs: "34", fiber: "2", sugar: "8", cholesterol: "46", protein: "10", sodium: "657" },
  { id: 39, recipe_id: 51, calories: "271 kcal", fat: "9", saturated_fat: "2", unsaturated_fat: "0", carbs: "48", fiber: "2", sugar: "35", cholesterol: "25", protein: "3", sodium: "133" },
  { id: 40, recipe_id: 61, calories: "489 kcal", fat: "25", saturated_fat: "11", unsaturated_fat: "0", carbs: "63", fiber: "2", sugar: "32", cholesterol: "55", protein: "5", sodium: "292" },
  { id: 41, recipe_id: 63, calories: "89 kcal", fat: "5", saturated_fat: "3", unsaturated_fat: "0", carbs: "11", fiber: "0", sugar: "8", cholesterol: "11", protein: "1", sodium: "24" },
  { id: 42, recipe_id: 64, calories: "434 kcal", fat: "27", saturated_fat: "11", unsaturated_fat: "0", carbs: "45", fiber: "2", sugar: "35", cholesterol: "24", protein: "6", sodium: "249" },
  { id: 43, recipe_id: 65, calories: "678 kcal", fat: "53", saturated_fat: "29", unsaturated_fat: "0", carbs: "46", fiber: "2", sugar: "40", cholesterol: "159", protein: "6", sodium: "419" },
  { id: 44, recipe_id: 66, calories: "162 kcal", fat: "1", saturated_fat: "0", unsaturated_fat: "0", carbs: "41", fiber: "3", sugar: "37", cholesterol: "0", protein: "2", sodium: "5" },
  { id: 45, recipe_id: 67, calories: "88 kcal", fat: "6", saturated_fat: "1", unsaturated_fat: "0", carbs: "9", fiber: "3", sugar: "5", cholesterol: "0", protein: "1", sodium: "121" },
  { id: 46, recipe_id: 68, calories: "350 kcal", fat: "32", saturated_fat: "4", unsaturated_fat: "0", carbs: "18", fiber: "8", sugar: "7", cholesterol: "0", protein: "3", sodium: "24" },
  { id: 47, recipe_id: 71, calories: "775 kcal", fat: "49", saturated_fat: "21", unsaturated_fat: "0", carbs: "37", fiber: "2", sugar: "2", cholesterol: "204", protein: "51", sodium: "1741" },
  { id: 48, recipe_id: 72, calories: "738 kcal", fat: "34", saturated_fat: "20", unsaturated_fat: "0", carbs: "99", fiber: "5", sugar: "44", cholesterol: "202", protein: "13", sodium: "477" },
  { id: 49, recipe_id: 73, calories: "652 kcal", fat: "41", saturated_fat: "18", unsaturated_fat: "0", carbs: "44", fiber: "1", sugar: "24", cholesterol: "259", protein: "27", sodium: "1267" },
  { id: 51, recipe_id: 77, calories: "760 kcal", fat: "39", saturated_fat: "21", unsaturated_fat: "0", carbs: "92", fiber: "4", sugar: "70", cholesterol: "106", protein: "7", sodium: "366" },
  { id: 52, recipe_id: 78, calories: "654 kcal", fat: "52", saturated_fat: "15", unsaturated_fat: "0", carbs: "23", fiber: "5", sugar: "11", cholesterol: "67", protein: "28", sodium: "1658" },
  {
    "id": 53,
    "recipe_id": 11,
    "calories": "350 kcal",
    "fat": "10",
    "saturated_fat": "3",
    "unsaturated_fat": "5",
    "carbs": "55",
    "fiber": "2",
    "sugar": "12",
    "cholesterol": "45",
    "protein": "8",
    "sodium": "400"
  },
  {
    "id": 54,
    "recipe_id": 13,
    "calories": "290 kcal",
    "fat": "12",
    "saturated_fat": "6",
    "unsaturated_fat": "4",
    "carbs": "35",
    "fiber": "2",
    "sugar": "8",
    "cholesterol": "155",
    "protein": "10",
    "sodium": "320"
  },
  {
    "id": 55,
    "recipe_id": 16,
    "calories": "250 kcal",
    "fat": "18",
    "saturated_fat": "2.5",
    "unsaturated_fat": "14",
    "carbs": "22",
    "fiber": "7",
    "sugar": "2",
    "cholesterol": "0",
    "protein": "6",
    "sodium": "220"
  },
  {
    "id": 56,
    "recipe_id": 17,
    "calories": "520 kcal",
    "fat": "35",
    "saturated_fat": "15",
    "unsaturated_fat": "15",
    "carbs": "32",
    "fiber": "2",
    "sugar": "2",
    "cholesterol": "320",
    "protein": "25",
    "sodium": "1020"
  },
  {
    "id": 57,
    "recipe_id": 18,
    "calories": "520 kcal",
    "fat": "30",
    "saturated_fat": "12",
    "unsaturated_fat": "15",
    "carbs": "35",
    "fiber": "4",
    "sugar": "3",
    "cholesterol": "275",
    "protein": "25",
    "sodium": "850"
  },
  {
    "id": 58,
    "recipe_id": 22,
    "calories": "170 kcal",
    "fat": "0",
    "saturated_fat": "0",
    "unsaturated_fat": "0",
    "carbs": "14",
    "fiber": "1",
    "sugar": "12",
    "cholesterol": "0",
    "protein": "0",
    "sodium": "5"
  },
  {
    "id": 59,
    "recipe_id": 41,
    "calories": "2 kcal",
    "fat": "0",
    "saturated_fat": "0",
    "unsaturated_fat": "0",
    "carbs": "0",
    "fiber": "0",
    "sugar": "0",
    "cholesterol": "0",
    "protein": "0.3",
    "sodium": "1"
  },
  {
    "id": 60,
    "recipe_id": 76,
    "calories": "20 kcal",
    "fat": "1",
    "saturated_fat": "0.2",
    "unsaturated_fat": "0.5",
    "carbs": "3",
    "fiber": "1",
    "sugar": "0",
    "cholesterol": "0",
    "protein": "1",
    "sodium": "5"
  },
  {
    "id": 61,
    "recipe_id": 78,
    "calories": "280 kcal",
    "fat": "12",
    "saturated_fat": "5",
    "unsaturated_fat": "6",
    "carbs": "25",
    "fiber": "5",
    "sugar": "7",
    "cholesterol": "50",
    "protein": "18",
    "sodium": "550"
  },
  {
    "id": 62,
    "recipe_id": 75,
    "calories": "210 kcal",
    "fat": "5",
    "saturated_fat": "1",
    "unsaturated_fat": "3",
    "carbs": "35",
    "fiber": "8",
    "sugar": "8",
    "cholesterol": "0",
    "protein": "8",
    "sodium": "550"
  },
  {
    "id": 63,
    "recipe_id": 70,
    "calories": "450 kcal",
    "fat": "22",
    "saturated_fat": "10",
    "unsaturated_fat": "10",
    "carbs": "45",
    "fiber": "5",
    "sugar": "4",
    "cholesterol": "40",
    "protein": "18",
    "sodium": "780"
  },
  {
    "id": 64,
    "recipe_id": 69,
    "calories": "150 kcal",
    "fat": "10",
    "saturated_fat": "1.5",
    "unsaturated_fat": "7",
    "carbs": "12",
    "fiber": "3",
    "sugar": "6",
    "cholesterol": "5",
    "protein": "1",
    "sodium": "220"
  },
  {
    "id": 65,
    "recipe_id": 62,
    "calories": "350 kcal",
    "fat": "20",
    "saturated_fat": "12",
    "unsaturated_fat": "6",
    "carbs": "28",
    "fiber": "2",
    "sugar": "3",
    "cholesterol": "55",
    "protein": "14",
    "sodium": "640"
  },
  {
    "id": 66,
    "recipe_id": 36,
    "calories": "94 kcal",
    "fat": "10",
    "saturated_fat": "1.5",
    "unsaturated_fat": "8",
    "carbs": "0",
    "fiber": "0",
    "sugar": "0",
    "cholesterol": "20",
    "protein": "0",
    "sodium": "200"
  },
  {
    "id": 67,
    "recipe_id": 55,
    "calories": "320 kcal",
    "fat": "14",
    "saturated_fat": "8",
    "unsaturated_fat": "5",
    "carbs": "45",
    "fiber": "3",
    "sugar": "24",
    "cholesterol": "35",
    "protein": "2",
    "sodium": "220"
  },
  {
    "id": 68,
    "recipe_id": 56,
    "calories": "320 kcal",
    "fat": "14",
    "saturated_fat": "7",
    "unsaturated_fat": "5",
    "carbs": "45",
    "fiber": "2",
    "sugar": "25",
    "cholesterol": "55",
    "protein": "4",
    "sodium": "300"
  },
  {
    "id": 69,
    "recipe_id": 57,
    "calories": "500 kcal",
    "fat": "28",
    "saturated_fat": "7",
    "unsaturated_fat": "18",
    "carbs": "57",
    "fiber": "3",
    "sugar": "36",
    "cholesterol": "75",
    "protein": "6",
    "sodium": "250"
  },
  {
    "id": 70,
    "recipe_id": 52,
    "calories": "540 kcal",
    "fat": "22",
    "saturated_fat": "8",
    "unsaturated_fat": "12",
    "carbs": "55",
    "fiber": "3",
    "sugar": "3",
    "cholesterol": "160",
    "protein": "22",
    "sodium": "900"
  },
  {
    "id": 71,
    "recipe_id": 53,
    "calories": "400 kcal",
    "fat": "12",
    "saturated_fat": "2",
    "unsaturated_fat": "9",
    "carbs": "60",
    "fiber": "6",
    "sugar": "7",
    "cholesterol": "0",
    "protein": "12",
    "sodium": "400"
  },
  {
    "id": 72,
    "recipe_id": 54,
    "calories": "480 kcal",
    "fat": "22",
    "saturated_fat": "12",
    "unsaturated_fat": "8",
    "carbs": "45",
    "fiber": "4",
    "sugar": "8",
    "cholesterol": "90",
    "protein": "26",
    "sodium": "850"
  },
  {
    "id": 73,
    "recipe_id": 44,
    "calories": "430 kcal",
    "fat": "25",
    "saturated_fat": "7",
    "unsaturated_fat": "16",
    "carbs": "0",
    "fiber": "0",
    "sugar": "0",
    "cholesterol": "150",
    "protein": "50",
    "sodium": "600"
  },
  {
    "id": 74,
    "recipe_id": 45,
    "calories": "350 kcal",
    "fat": "20",
    "saturated_fat": "4",
    "unsaturated_fat": "14",
    "carbs": "0",
    "fiber": "0",
    "sugar": "0",
    "cholesterol": "95",
    "protein": "38",
    "sodium": "480"
  }
]
