export interface Ingredient {
  id: number;
  recipe_id: number;
  ingredient: string;
}

export interface Direction {
  id: number;
  recipe_id: number;
  instruction: string;
}

export interface Nutrition {
  recipe_id: number;
  calories?: string;
  fat?: string;
  saturated_fat?: string;
  unsaturated_fat?: string;
  carbs?: string;
  fiber?: string;
  sugar?: string;
  cholesterol?: string | "0";
  protein?: string;
  sodium?: string;
}

// Ingredients
export const ingredientsData: Ingredient[] = [
  // Appetizer (recipe_id 1)
  { id: 1, recipe_id: 1, ingredient: "1 cup diced tomatoes" },
  { id: 2, recipe_id: 1, ingredient: "2 tbsp olive oil" },
  { id: 3, recipe_id: 1, ingredient: "1 clove garlic, minced" },

  { id: 4, recipe_id: 2, ingredient: "12 mushrooms" },
  { id: 5, recipe_id: 2, ingredient: "1/4 cup breadcrumbs" },
  { id: 6, recipe_id: 2, ingredient: "2 tbsp parmesan cheese" },

  { id: 7, recipe_id: 3, ingredient: "Cherry tomatoes" },
  { id: 8, recipe_id: 3, ingredient: "Fresh mozzarella balls" },
  { id: 9, recipe_id: 3, ingredient: "Basil leaves" },

  { id: 10, recipe_id: 4, ingredient: "1 cup lemon juice" },
  { id: 11, recipe_id: 4, ingredient: "4 cups water" },
  { id: 12, recipe_id: 4, ingredient: "1/2 cup sugar" },
  {
    id: 23,
    recipe_id: 5,
    ingredient: "2 pounds red potatoes"
  },
  {
    id: 24,
    recipe_id: 5,
    ingredient: "3 hard-cooked eggs, chopped"
  },
  {
    id: 25,
    recipe_id: 5,
    ingredient: "0.5 cup sour cream"
  },
  {
    id: 26,
    recipe_id: 5,
    ingredient: "0.5 cup mayonnaise"
  },
  {
    id: 27,
    recipe_id: 5,
    ingredient: "0.5 (4 ounce) jar chopped pimento peppers"
  },
  {
    id: 28,
    recipe_id: 5,
    ingredient: "2 green onions, chopped"
  },
  {
    id: 29,
    recipe_id: 5,
    ingredient: "2 slices cooked bacon, chopped"
  },
  {
    id: 30,
    recipe_id: 5,
    ingredient: "2 tablespoons yellow mustard"
  },
  {
    id: 31,
    recipe_id: 5,
    ingredient: "1 tablespoon white sugar"
  },
  {
    id: 32,
    recipe_id: 5,
    ingredient: "1 tablespoon red wine vinegar"
  },
  {
    id: 33,
    recipe_id: 5,
    ingredient: "0.5 teaspoon salt"
  },
  {
    id: 34,
    recipe_id: 5,
    ingredient: "0.5 teaspoon ground black pepper"
  },
  {
    id: 35,
    recipe_id: 5,
    ingredient: "0.5 teaspoon celery seed"
  },
  {
    id: 36,
    recipe_id: 5,
    ingredient: "0.25 teaspoon garlic powder"
  },
  {
    id: 37,
    recipe_id: 5,
    ingredient: "1 pinch paprika, or as desired"
  },

  { id: 38, recipe_id: 6, ingredient: "2 cups cherries, pitted" },
  { id: 39, recipe_id: 6, ingredient: "0.6 cup white sugar" },
  { id: 40, recipe_id: 6, ingredient: "0.5 cup water" },
  { id: 41, recipe_id: 6, ingredient: "1 teaspoon ground cinnamon" },
  { id: 42, recipe_id: 6, ingredient: "1 cup sifted all-purpose flour" },
  { id: 43, recipe_id: 6, ingredient: "2 teaspoons baking powder" },
  { id: 44, recipe_id: 6, ingredient: "0.25 teaspoon salt" },
  { id: 45, recipe_id: 6, ingredient: "0.5 cup milk" },

  { id: 46, recipe_id: 7, ingredient: "4 limes, juiced" },
  { id: 47, recipe_id: 7, ingredient: "1 cup white sugar" },
  { id: 48, recipe_id: 7, ingredient: "2 sprigs fresh mint" },
  { id: 49, recipe_id: 7, ingredient: "0.5 gallon water" },
  { id: 50, recipe_id: 7, ingredient: "1 fresh jalapeno pepper, sliced" },

  { id: 51, recipe_id: 8, ingredient: "0.5 cup butter" },
  { id: 52, recipe_id: 8, ingredient: "2 (1 ounce) squares unsweetened chocolate, chopped" },
  { id: 53, recipe_id: 8, ingredient: "2 eggs" },
  { id: 54, recipe_id: 8, ingredient: "1 cup white sugar" },
  { id: 55, recipe_id: 8, ingredient: "1 teaspoon vanilla extract" },
  { id: 56, recipe_id: 8, ingredient: "3 tablespoons matzo meal" },
  { id: 57, recipe_id: 8, ingredient: "0.5 cup potato starch" },
  { id: 58, recipe_id: 8, ingredient: "0.5 teaspoon salt" },
  { id: 59, recipe_id: 8, ingredient: "0.5 cup chopped walnuts" },
  { id: 60, recipe_id: 8, ingredient: "0.5 cup semisweet chocolate chips" },

  { id: 61, recipe_id: 9, ingredient: "2 tomatoes, cut into chunks" },
  { id: 62, recipe_id: 9, ingredient: "1 large zucchini, cut into chunks" },
  { id: 63, recipe_id: 9, ingredient: "1 large yellow squash, cut into chunks" },
  { id: 64, recipe_id: 9, ingredient: "0.5 green bell pepper, diced" },
  { id: 65, recipe_id: 9, ingredient: "0.5 sweet red onion, chopped" },
  { id: 66, recipe_id: 9, ingredient: "2 cloves garlic, minced" },
  { id: 67, recipe_id: 9, ingredient: "1 teaspoon dried basil" },
  { id: 68, recipe_id: 9, ingredient: "0.5 teaspoon salt, or to taste" },
  { id: 69, recipe_id: 9, ingredient: "0.25 cup olive oil" },
  { id: 70, recipe_id: 9, ingredient: "0.25 cup red wine vinegar" },
  { id: 71, recipe_id: 9, ingredient: "3 tablespoons water" },

  { id: 72, recipe_id: 10, ingredient: "1 medium firm peach, halved and pitted" },
  { id: 73, recipe_id: 10, ingredient: "2 tablespoons unsalted butter" },
  { id: 74, recipe_id: 10, ingredient: "1 teaspoon light brown sugar" },
  { id: 75, recipe_id: 10, ingredient: "0.25 teaspoon ground cinnamon" },
  { id: 76, recipe_id: 10, ingredient: "2 scoops vanilla ice cream" },

  { id: 77, recipe_id: 12, ingredient: "1 cup white sugar" },
  { id: 78, recipe_id: 12, ingredient: "5 tablespoons butter, cut into slices" },
  { id: 79, recipe_id: 12, ingredient: "0.5 cup heavy cream" },
  { id: 80, recipe_id: 12, ingredient: "1 tablespoon heavy whipping cream" },
  { id: 81, recipe_id: 12, ingredient: "1 pinch sea salt to taste" },
  { id: 77, recipe_id: 12, "ingredient": "1 cup white sugar" },
  { id: 78, recipe_id: 12, "ingredient": "5 tablespoons butter, cut into slices" },
  { id: 79, recipe_id: 12, "ingredient": "0.5 cup heavy cream" },
  { id: 80, recipe_id: 12, "ingredient": "1 tablespoon heavy whipping cream" },
  { id: 81, recipe_id: 12, "ingredient": "1 pinch sea salt to taste" },
  { id: 82, recipe_id: 14, "ingredient": "0.5 cup water" },
  { id: 83, recipe_id: 14, "ingredient": "0.33 cup dry lemonade-flavored drink mix" },
  { id: 84, recipe_id: 14, "ingredient": "3 cups ice cubes" },
  { id: 85, recipe_id: 14, "ingredient": "1 cup strawberries" },
  { id: 86, recipe_id: 15, "ingredient": "1 cup boiling water" },
  { id: 87, recipe_id: 15, "ingredient": "1 cup couscous" },
  { id: 88, recipe_id: 15, "ingredient": "4 tomatoes" },
  { id: 89, recipe_id: 15, "ingredient": "16 leaves fresh basil" },
  { id: 90, recipe_id: 15, "ingredient": "8 ounces fresh mozzarella cheese, diced" },
  { id: 91, recipe_id: 15, "ingredient": "0.25 cup balsamic vinegar, or to taste" },
  { id: 92, recipe_id: 19, "ingredient": "0.25 cup butter" },
  { id: 93, recipe_id: 19, "ingredient": "1.25 cups packed brown sugar" },
  { id: 94, recipe_id: 19, "ingredient": "16 large marshmallows" },
  { id: 95, recipe_id: 19, "ingredient": "2 tablespoons light corn syrup" },
  { id: 96, recipe_id: 19, "ingredient": "1 dash salt" },
  { id: 97, recipe_id: 19, "ingredient": "1 cup evaporated milk" },
  { id: 98, recipe_id: 19, "ingredient": "0.5 cup chopped pecans, toasted" },
  { id: 99, recipe_id: 19, "ingredient": "1 teaspoon vanilla extract" },
  { id: 100, recipe_id: 20, "ingredient": "1.75 cups all-purpose flour" },
  { id: 101, recipe_id: 20, "ingredient": "0.5 cup finely chopped crystallized ginger" },
  { id: 102, recipe_id: 20, "ingredient": "1 teaspoon ground ginger" },
  { id: 103, recipe_id: 20, "ingredient": "0.5 teaspoon baking powder" },
  { id: 104, recipe_id: 20, "ingredient": "0.5 teaspoon baking soda" },
  { id: 105, recipe_id: 20, "ingredient": "0.5 teaspoon salt" },
  { id: 106, recipe_id: 20, "ingredient": "0.25 teaspoon ground nutmeg" },
  { id: 107, recipe_id: 20, "ingredient": "0.5 cup unsalted butter, softened" },
  { id: 108, recipe_id: 20, "ingredient": "1 cup brown sugar" },
  { id: 109, recipe_id: 20, "ingredient": "1 large egg, at room temperature" },
  { id: 110, recipe_id: 20, "ingredient": "1.5 teaspoons vanilla extract" },
  { id: 111, recipe_id: 20, "ingredient": "1.5 cups finely chopped rhubarb" },
  { id: 112, recipe_id: 21, "ingredient": "1 (15.25 ounce) package vanilla flavored cake mix" },
  { id: 113, recipe_id: 21, "ingredient": "1 (15.25 ounce) package strawberry cake mix" },
  { id: 114, recipe_id: 21, "ingredient": "6 large eggs, divided" },
  { id: 115, recipe_id: 21, "ingredient": "2 cups water, divided" },
  { id: 116, recipe_id: 21, "ingredient": "1 cup canola oil, divided" },
  { id: 117, recipe_id: 21, "ingredient": "1.5 cups unsalted butter, softened" },
  { id: 118, recipe_id: 21, "ingredient": "4 cups powdered sugar" },
  { id: 119, recipe_id: 21, "ingredient": "6 tablespoons heavy whipping cream" },
  { id: 120, recipe_id: 21, "ingredient": "2 teaspoons vanilla extract" },
  { id: 121, recipe_id: 21, "ingredient": "3 cups freeze-dried strawberries" },
  { id: 122, recipe_id: 21, "ingredient": "20 speculoos cookies (such as Lotus Biscoff®)" },
  { id: 123, recipe_id: 21, "ingredient": "3 tablespoons unsalted butter, melted" },
  { id: 124, recipe_id: 23, "ingredient": "1.5 cups water" },
  { id: 125, recipe_id: 23, "ingredient": "1 cup uncooked basmati rice, rinsed and drained" },
  { id: 126, recipe_id: 23, "ingredient": "0.75 pound plums, pitted and chopped" },
  { id: 127, recipe_id: 23, "ingredient": "0.5 medium red onion, minced" },
  { id: 128, recipe_id: 23, "ingredient": "3 habanero peppers, seeded and minced" },
  { id: 129, recipe_id: 23, "ingredient": "3 tablespoons minced fresh cilantro" },
  { id: 130, recipe_id: 23, "ingredient": "1 teaspoon sugar" },
  { id: 131, recipe_id: 23, "ingredient": "0.75 pound boneless, skinless chicken breasts" },
  { id: 132, recipe_id: 23, "ingredient": "2 teaspoons fresh rosemary, minced" },
  { id: 133, recipe_id: 23, "ingredient": "salt and pepper to taste" },
  { id: 134, recipe_id: 23, "ingredient": "2 teaspoons vegetable oil" },
  { id: 135, recipe_id: 24, "ingredient": "1 (16 ounce) package penne pasta" },
  { id: 136, recipe_id: 24, "ingredient": "2 cups shredded kale" },
  { id: 137, recipe_id: 24, "ingredient": "2 medium carrots, shredded" },
  { id: 138, recipe_id: 24, "ingredient": "1.5 cups cherry tomatoes, halved" },
  { id: 139, recipe_id: 24, "ingredient": "1 cup sliced black olives, drained" },
  { id: 140, recipe_id: 24, "ingredient": "1 cucumber, chopped" },
  { id: 141, recipe_id: 24, "ingredient": "1 medium red bell pepper, chopped" },
  { id: 142, recipe_id: 24, "ingredient": "0.5 shallot, chopped" },
  { id: 143, recipe_id: 24, "ingredient": "1 cup Greek salad dressing" },
  { id: 144, recipe_id: 24, "ingredient": "2 tablespoons mayonnaise" },
  { id: 145, recipe_id: 25, "ingredient": "1 fresh peach, chopped" },
  { id: 146, recipe_id: 25, "ingredient": "2 plums, pitted and chopped" },
  { id: 147, recipe_id: 25, "ingredient": "1 cup chopped tomato" },
  { id: 148, recipe_id: 25, "ingredient": "1 cup pitted and halved cherries" },
  { id: 149, recipe_id: 25, "ingredient": "2 tablespoons chopped fresh parsley" },
  { id: 150, recipe_id: 25, "ingredient": "1 teaspoon lemon zest" },
  { id: 151, recipe_id: 25, "ingredient": "1 tablespoon lemon juice" },
  { id: 152, recipe_id: 25, "ingredient": "1 clove garlic, minced" },
  { id: 153, recipe_id: 25, "ingredient": "0.25 teaspoon salt" },
  { id: 154, recipe_id: 25, "ingredient": "0.125 teaspoon ground black pepper" },
  { id: 155, recipe_id: 25, "ingredient": "1 tablespoon extra-virgin olive oil" },
  { id: 156, recipe_id: 26, "ingredient": "0.25 cup all-purpose flour" },
  { id: 157, recipe_id: 26, "ingredient": "1.5 tablespoons brown sugar" },
  { id: 158, recipe_id: 26, "ingredient": "0.5 teaspoon baking powder" },
  { id: 159, recipe_id: 26, "ingredient": "1 dash salt" },
  { id: 160, recipe_id: 26, "ingredient": "0.25 teaspoon cinnamon" },
  { id: 161, recipe_id: 26, "ingredient": "0.25 teaspoon vanilla extract" },
  { id: 162, recipe_id: 26, "ingredient": "3 tablespoons almond milk" },
  { id: 163, recipe_id: 26, "ingredient": "0.5 tablespoon vegetable oil" },
  { id: 164, recipe_id: 26, "ingredient": "3 tablespoons shredded zucchini" },
  { id: 165, recipe_id: 26, "ingredient": "0.5 tablespoon chopped walnuts" },
  { id: 166, recipe_id: 27, "ingredient": "1 cup biscuit baking mix" },
  { id: 167, recipe_id: 27, "ingredient": "0.25 cup grated Parmesan cheese" },
  { id: 168, recipe_id: 27, "ingredient": "1 teaspoon dried parsley" },
  { id: 169, recipe_id: 27, "ingredient": "0.5 teaspoon garlic powder" },
  { id: 170, recipe_id: 27, "ingredient": "0.5 teaspoon seasoning salt" },
  { id: 171, recipe_id: 27, "ingredient": "0.5 teaspoon dried oregano" },
  { id: 172, recipe_id: 27, "ingredient": "0.25 teaspoon salt" },
  { id: 173, recipe_id: 27, "ingredient": "0.25 teaspoon ground black pepper" },
  { id: 174, recipe_id: 27, "ingredient": "4 eggs" },
  { id: 175, recipe_id: 27, "ingredient": "0.33300000429153 cup vegetable oil" },
  { id: 176, recipe_id: 27, "ingredient": "0.25 cup grated onion" },
  { id: 177, recipe_id: 27, "ingredient": "2 zucchini, thinly sliced" },
  { id: 178, recipe_id: 28, "ingredient": "1 1/2 cups frozen blackberries" },
  { id: 179, recipe_id: 28, "ingredient": "1/4 cup white sugar, or to taste" },
  { id: 180, recipe_id: 28, "ingredient": "1 tablespoon fresh lemon juice" },
  { id: 181, recipe_id: 28, "ingredient": "1/4 teaspoon freshly grated lemon zest, or to taste" },
  { id: 182, recipe_id: 28, "ingredient": "1 teaspoon cornstarch" },
  { id: 183, recipe_id: 28, "ingredient": "1 tablespoon water" },
  { id: 184, recipe_id: 28, "ingredient": "1/2 cup unsalted butter, melted" },
  { id: 185, recipe_id: 28, "ingredient": "1 cup firmly packed light brown sugar" },
  { id: 186, recipe_id: 28, "ingredient": "1/2 teaspoon salt" },
  { id: 187, recipe_id: 28, "ingredient": "1 egg, room temp" },
  { id: 188, recipe_id: 28, "ingredient": "1 egg yolk, room temp" },
  { id: 189, recipe_id: 28, "ingredient": "2 teaspoons vanilla extract" },
  { id: 190, recipe_id: 28, "ingredient": "1/2 cup unsweetened cocoa powder" },
  { id: 191, recipe_id: 28, "ingredient": "1/2 cup all-purpose flour" },
  { id: 192, recipe_id: 28, "ingredient": "1/4 teaspoon baking soda" },
  { id: 193, recipe_id: 28, "ingredient": "8 oz full fat cream cheese, room temp" },
  { id: 194, recipe_id: 28, "ingredient": "1/3 cup white sugar" },
  { id: 195, recipe_id: 28, "ingredient": "Pinch of salt" },
  { id: 196, recipe_id: 28, "ingredient": "Pinch of ground nutmeg" },
  { id: 197, recipe_id: 28, "ingredient": "1 egg white, room temp" },
  { id: 198, recipe_id: 28, "ingredient": "2 teaspoons fresh lemon juice" },
  { id: 199, recipe_id: 28, "ingredient": "1 teaspoon vanilla extract" },
  { id: 200, recipe_id: 28, "ingredient": "3/4 cup heavy whipping cream, room temp" },
  { id: 201, recipe_id: 29, "ingredient": "3 pounds fresh strawberries, hulled and sliced" },
  { id: 202, recipe_id: 29, "ingredient": "0.25 cup white sugar" },
  { id: 203, recipe_id: 29, "ingredient": "1 quart heavy cream" },
  { id: 204, recipe_id: 29, "ingredient": "1 (6 ounce) container lemon yogurt" },
  { id: 205, recipe_id: 29, "ingredient": "1 (3.3 ounce) package instant white chocolate pudding mix" },
  { id: 206, recipe_id: 29, "ingredient": "2 tablespoons coconut-flavored rum, or to taste, divided" },
  { id: 207, recipe_id: 29, "ingredient": "2 (16 ounce) prepared pound cakes, cubed" },
  { id: 208, recipe_id: 29, "ingredient": "2 pints fresh blueberries, or as needed" },
  { id: 209, recipe_id: 30, "ingredient": "2 cups blueberries" },
  { id: 210, recipe_id: 30, "ingredient": "1 cup white sugar" },
  { id: 211, recipe_id: 30, "ingredient": "0.25 cup water" },
  { id: 212, recipe_id: 30, "ingredient": "1 tablespoon butter" },
  { id: 213, recipe_id: 30, "ingredient": "1 cup all-purpose flour" },
  { id: 214, recipe_id: 30, "ingredient": "2 teaspoons baking powder" },
  { id: 215, recipe_id: 30, "ingredient": "0.125 teaspoon salt" },
  { id: 216, recipe_id: 30, "ingredient": "0.5 cup milk" },
  { id: 217, recipe_id: 31, "ingredient": "8 ounces fettuccine, cooked according to package instructions, drained" },
  { id: 218, recipe_id: 31, "ingredient": "1 Tablespoon unsalted butter" },
  { id: 219, recipe_id: 31, "ingredient": "1 Tablespoon olive oil" },
  { id: 220, recipe_id: 31, "ingredient": "4 cloves garlic, divided" },
  { id: 221, recipe_id: 31, "ingredient": "1 pound shrimp - peeled, deveined, and patted dry" },
  { id: 222, recipe_id: 31, "ingredient": "Pinch salt" },
  { id: 223, recipe_id: 31, "ingredient": "1 large shallot, sliced thinly, about 1/2 cup" },
  { id: 224, recipe_id: 31, "ingredient": "1/2 teaspoon red pepper flakes" },
  { id: 225, recipe_id: 31, "ingredient": "2 cups cherry tomatoes, halved" },
  { id: 226, recipe_id: 31, "ingredient": "1/4 cup flat-leaf parsley, minced" },
  { id: 227, recipe_id: 31, "ingredient": "1/2 cup dry white wine" },
  { id: 228, recipe_id: 31, "ingredient": "2 cups fresh spinach, roughly chopped" },
  { id: 229, recipe_id: 31, "ingredient": "1 cup heavy cream" },
  { id: 230, recipe_id: 31, "ingredient": "Additional flat leaf parsley sprigs for optional garnish" },
  { id: 231, recipe_id: 32, "ingredient": "6 fresh raspberries, divided" },
  { id: 232, recipe_id: 32, "ingredient": "1 tablespoon raspberry flavored liqueur" },
  { id: 233, recipe_id: 32, "ingredient": "2 tablespoons vodka" },
  { id: 234, recipe_id: 32, "ingredient": "0.75 cup lemonade" },
  { id: 235, recipe_id: 33, "ingredient": "2.5 cups finely chopped rhubarb" },
  { id: 236, recipe_id: 33, "ingredient": "0.5 cup white sugar" },
  { id: 237, recipe_id: 33, "ingredient": "1 pinch salt" },
  { id: 238, recipe_id: 33, "ingredient": "1 teaspoon lemon juice" },
  { id: 239, recipe_id: 33, "ingredient": "2.5 cups all-purpose flour" },
  { id: 240, recipe_id: 33, "ingredient": "1.5 teaspoons baking powder" },
  { id: 241, recipe_id: 33, "ingredient": "0.75 teaspoon salt" },
  { id: 242, recipe_id: 33, "ingredient": "0.5 teaspoon baking soda" },
  { id: 243, recipe_id: 33, "ingredient": "0.5 cup unsalted butter, softened" },
  { id: 244, recipe_id: 33, "ingredient": "0.25 cup vegetable oil" },
  { id: 245, recipe_id: 33, "ingredient": "1.75 cups white sugar" },
  { id: 246, recipe_id: 33, "ingredient": "3 large eggs, at room temperature" },
  { id: 247, recipe_id: 33, "ingredient": "2 teaspoons vanilla extract" },
  { id: 248, recipe_id: 33, "ingredient": "0.5 teaspoon almond extract" },
  { id: 249, recipe_id: 33, "ingredient": "1.5 cups buttermilk, at room temperature" },
  { id: 250, recipe_id: 34, "ingredient": "1 cup sugar" },
  { id: 251, recipe_id: 34, "ingredient": "1 cup water" },
  { id: 252, recipe_id: 34, "ingredient": "2 cups chopped mango" },
  { id: 253, recipe_id: 34, "ingredient": "1 cup water" },
  { id: 254, recipe_id: 34, "ingredient": "1 cup lemon juice" },
  { id: 255, recipe_id: 34, "ingredient": "2 cups ice" },
  { id: 256, recipe_id: 35, "ingredient": "2/3 \tcup mayonnaise" },
  { id: 257, recipe_id: 35, "ingredient": "3\tTablespoons ketchup" },
  { id: 258, recipe_id: 35, "ingredient": "2\tTablespoons sweet pickle relish" },
  { id: 259, recipe_id: 35, "ingredient": "1 1/2 \tteaspoon vinegar" },
  { id: 260, recipe_id: 35, "ingredient": "1/2 \tteaspoon sugar" },
  { id: 261, recipe_id: 35, "ingredient": "1/4 \tteaspoon salt" },
  { id: 262, recipe_id: 35, "ingredient": "1/4 teaspoon pepper optional" },
  { id: 263, recipe_id: 37, "ingredient": "4 cups cubed seeded watermelon" },
  { id: 264, recipe_id: 37, "ingredient": "2 roma (plum) tomatoes, seeded and chopped" },
  { id: 265, recipe_id: 37, "ingredient": "1 red bell pepper, chopped" },
  { id: 266, recipe_id: 37, "ingredient": "0.5 English (seedless) cucumber - peeled, seeded, and cubed" },
  { id: 267, recipe_id: 37, "ingredient": "2 tablespoons minced shallot" },
  { id: 268, recipe_id: 37, "ingredient": "2 tablespoons fresh lime juice" },
  { id: 269, recipe_id: 37, "ingredient": "1 tablespoon apple cider vinegar" },
  { id: 270, recipe_id: 37, "ingredient": "1.5 teaspoons salt, or to taste" },
  { id: 271, recipe_id: 37, "ingredient": "0.25 teaspoon freshly ground black pepper" },
  { id: 272, recipe_id: 37, "ingredient": "2 tablespoons crumbled feta cheese" },
  { id: 273, recipe_id: 37, "ingredient": "2 tablespoons minced fresh cilantro" },
  { id: 274, recipe_id: 38, "ingredient": "3 sprigs fresh dill" },
  { id: 275, recipe_id: 38, "ingredient": "0.25 cup toasted pine nuts" },
  { id: 276, recipe_id: 38, "ingredient": "0.5 cup fresh parsley" },
  { id: 277, recipe_id: 38, "ingredient": "1 large clove garlic" },
  { id: 278, recipe_id: 38, "ingredient": "0.25 cup freshly grated Parmesan cheese, or more to taste" },
  { id: 279, recipe_id: 38, "ingredient": "3 tablespoons olive oil, divided, or as needed" },
  { id: 280, recipe_id: 38, "ingredient": "0.25 medium lemon, or to taste" },
  { id: 281, recipe_id: 38, "ingredient": "0.125 teaspoon salt, or to taste" },
  { id: 282, recipe_id: 38, "ingredient": "0.125 teaspoon ground black pepper, or to taste" },
  { id: 283, recipe_id: 39, "ingredient": "2 cups sweet kernel corn" },
  { id: 284, recipe_id: 39, "ingredient": "0.75 cup diced tomato" },
  { id: 285, recipe_id: 39, "ingredient": "0.5 cup diced orange bell pepper" },
  { id: 286, recipe_id: 39, "ingredient": "0.5 cup chopped celery" },
  { id: 287, recipe_id: 39, "ingredient": "0.25 cup diced red onion" },
  { id: 288, recipe_id: 39, "ingredient": "1 clove garlic, minced" },
  { id: 289, recipe_id: 39, "ingredient": "0.5 cup prepared ranch salad dressing" },
  { id: 290, recipe_id: 39, "ingredient": "0.5 cup chopped fresh cilantro, divided" },
  { id: 291, recipe_id: 40, "ingredient": "4 teaspoons canola oil, divided" },
  { id: 292, recipe_id: 40, "ingredient": "2 eggs, beaten" },
  { id: 293, recipe_id: 40, "ingredient": "2 carrots, chopped" },
  { id: 294, recipe_id: 40, "ingredient": "salt and ground black pepper to taste" },
  { id: 295, recipe_id: 40, "ingredient": "3 cloves garlic, crushed" },
  { id: 296, recipe_id: 40, "ingredient": "1 cup frozen peas" },
  { id: 297, recipe_id: 40, "ingredient": "4 scallions, minced" },
  { id: 298, recipe_id: 40, "ingredient": "4 cups cooked rice" },
  { id: 299, recipe_id: 40, "ingredient": "1 teaspoon soy sauce, or to taste" },
  { id: 300, recipe_id: 42, "ingredient": "4 slices brioche bread" },
  { id: 301, recipe_id: 42, "ingredient": "0.5 cup lemon curd" },
  { id: 302, recipe_id: 42, "ingredient": "0.5 cup blueberries" },
  { id: 303, recipe_id: 42, "ingredient": "2 large eggs" },
  { id: 304, recipe_id: 42, "ingredient": "2 tablespoons milk" },
  { id: 305, recipe_id: 42, "ingredient": "2 tablespoons unsalted butter" },
  { id: 306, recipe_id: 42, "ingredient": "1 teaspoon confectioners' sugar" },
  { id: 307, recipe_id: 43, "ingredient": "4 (8 ounce) boneless, skinless chicken breasts" },
  { id: 308, recipe_id: 43, "ingredient": "0.25 cup red wine vinegar" },
  { id: 309, recipe_id: 43, "ingredient": "2 teaspoons kosher salt" },
  { id: 310, recipe_id: 43, "ingredient": "1 teaspoon freshly ground black pepper" },
  { id: 311, recipe_id: 43, "ingredient": "0.25 teaspoon cayenne pepper" },
  { id: 312, recipe_id: 43, "ingredient": "0.5 teaspoon dried thyme" },
  { id: 313, recipe_id: 43, "ingredient": "0.5 teaspoon dried oregano" },
  { id: 314, recipe_id: 43, "ingredient": "0.5 teaspoon dried rosemary" },
  { id: 315, recipe_id: 43, "ingredient": "0.5 teaspoon garlic powder" },
  { id: 316, recipe_id: 43, "ingredient": "0.25 cup olive oil" },
  { id: 317, recipe_id: 43, "ingredient": "1 drizzle olive oil, or as needed" },
  { id: 318, recipe_id: 43, "ingredient": "2 tablespoons chopped Italian parsley" },
  { id: 319, recipe_id: 43, "ingredient": "2 tablespoons chopped fresh mint" },
  { id: 320, recipe_id: 43, "ingredient": "1 cup full-fat Greek yogurt" },
  { id: 321, recipe_id: 43, "ingredient": "8 ounces feta cheese" },
  { id: 322, recipe_id: 43, "ingredient": "1 teaspoon finely crushed garlic, or to taste" },
  { id: 323, recipe_id: 43, "ingredient": "1 tablespoon chopped fresh mint" },
  { id: 324, recipe_id: 43, "ingredient": "1 teaspoon lemon zest" },
  { id: 325, recipe_id: 46, "ingredient": "1\t(8 count) pack hotdogs" },
  { id: 326, recipe_id: 46, "ingredient": "1/2\tcup garlic butter, melted" },
  { id: 327, recipe_id: 46, "ingredient": "1\t(8 count) pack hotdog buns" },
  { id: 328, recipe_id: 46, "ingredient": "2\tcups shredded cheese" },
  { id: 329, recipe_id: 47, "ingredient": "3 teaspoons butter" },
  { id: 330, recipe_id: 47, "ingredient": "3 ears fresh corn, husks and silks removed" },
  { id: 331, recipe_id: 47, "ingredient": "1 teaspoon garlic powder" },
  { id: 332, recipe_id: 47, "ingredient": "1 (15 ounce) can black beans, drained" },
  { id: 333, recipe_id: 47, "ingredient": "0.25 cup chopped fresh cilantro" },
  { id: 334, recipe_id: 47, "ingredient": "0.25 cup olive oil" },
  { id: 335, recipe_id: 47, "ingredient": "2 tablespoons red wine vinegar" },
  { id: 336, recipe_id: 47, "ingredient": "2 tablespoons lime juice" },
  { id: 337, recipe_id: 47, "ingredient": "1.5 teaspoons minced garlic" },
  { id: 338, recipe_id: 47, "ingredient": "1 teaspoon white sugar" },
  { id: 339, recipe_id: 47, "ingredient": "0.5 teaspoon ground cumin" },
  { id: 340, recipe_id: 47, "ingredient": "0.5 teaspoon chili powder" },
  { id: 341, recipe_id: 47, "ingredient": "0.25 teaspoon salt" },
  { id: 342, recipe_id: 47, "ingredient": "0.25 teaspoon black pepper" },
  { id: 343, recipe_id: 48, "ingredient": "1 tablespoon olive oil" },
  { id: 344, recipe_id: 48, "ingredient": "1 small onion, finely chopped" },
  { id: 345, recipe_id: 48, "ingredient": "1 lb. ground sirloin" },
  { id: 346, recipe_id: 48, "ingredient": "2 tablespoons low sodium Taco seasoning" },
  { id: 347, recipe_id: 48, "ingredient": "8 ounces processed American cheese, such as Velveeta, cut into large chunks" },
  { id: 348, recipe_id: 48, "ingredient": "1 (10 ounce) can diced tomatoes with green chiles, such as Rotel" },
  { id: 349, recipe_id: 48, "ingredient": "8 to 10 crunchy taco shells" },
  { id: 350, recipe_id: 48, "ingredient": "shredded iceberglettuce" },
  { id: 351, recipe_id: 48, "ingredient": "Optional: desired toppings such as diced tomato, hot sauceand sour cream" },
  { id: 352, recipe_id: 49, "ingredient": "1 cup white vinegar" },
  { id: 353, recipe_id: 49, "ingredient": "0.5 cup white sugar" },
  { id: 354, recipe_id: 49, "ingredient": "0.5 cup water" },
  { id: 355, recipe_id: 49, "ingredient": "1 tablespoon chopped fresh dill" },
  { id: 356, recipe_id: 49, "ingredient": "2 teaspoons salt" },
  { id: 357, recipe_id: 49, "ingredient": "2 cucumbers, peeled and thinly sliced" },
  { id: 358, recipe_id: 49, "ingredient": "0.33333334326744 cup sour cream" },
  { id: 359, recipe_id: 50, "ingredient": "1 cup cornmeal" },
  { id: 360, recipe_id: 50, "ingredient": "1 cup all-purpose flour, sifted" },
  { id: 361, recipe_id: 50, "ingredient": "1/4 cup sugar" },
  { id: 362, recipe_id: 50, "ingredient": "1 tablespoon baking powder" },
  { id: 363, recipe_id: 50, "ingredient": "1 teaspoon salt" },
  { id: 364, recipe_id: 50, "ingredient": "1 teaspoon pepper" },
  { id: 365, recipe_id: 50, "ingredient": "1/4 cup vegetable oil" },
  { id: 366, recipe_id: 50, "ingredient": "2 jalapenos, seeded and diced" },
  { id: 367, recipe_id: 50, "ingredient": "1 small yellow onion, minced" },
  { id: 368, recipe_id: 50, "ingredient": "3/4 cup shredded sharp Cheddar cheese, divided" },
  { id: 369, recipe_id: 50, "ingredient": "1 egg, beaten" },
  { id: 370, recipe_id: 50, "ingredient": "1 cup buttermilk" },
  { id: 371, recipe_id: 50, "ingredient": "1 tablespoon vegetable oil, or as needed" },
  { id: 372, recipe_id: 51, "ingredient": "1 recipe pastry for a single 9-inch pie crust" },
  { id: 373, recipe_id: 51, "ingredient": "1 (28 ounce) can sliced peaches, drained" },
  { id: 374, recipe_id: 51, "ingredient": "1 cup white sugar" },
  { id: 375, recipe_id: 51, "ingredient": "1 egg" },
  { id: 376, recipe_id: 51, "ingredient": "1 tablespoon all-purpose flour" },
  { id: 377, recipe_id: 51, "ingredient": "1 teaspoon butter" },
  { id: 378, recipe_id: 51, "ingredient": "0.25 teaspoon ground cinnamon, or to taste" },
  { id: 379, recipe_id: 61, "ingredient": "0.75 cup white sugar" },
  { id: 380, recipe_id: 61, "ingredient": "2 tablespoons all-purpose flour" },
  { id: 381, recipe_id: 61, "ingredient": "0.25 teaspoon salt" },
  { id: 382, recipe_id: 61, "ingredient": "1 cup sour cream" },
  { id: 383, recipe_id: 61, "ingredient": "1 egg, lightly beaten" },
  { id: 384, recipe_id: 61, "ingredient": "0.5 teaspoon vanilla extract" },
  { id: 385, recipe_id: 61, "ingredient": "2 cups sliced peaches" },
  { id: 386, recipe_id: 61, "ingredient": "1 unbaked pie crust" },
  { id: 387, recipe_id: 61, "ingredient": "1/3 cup all-purpose flour" },
  { id: 388, recipe_id: 61, "ingredient": "1/3 cup white sugar" },
  { id: 389, recipe_id: 61, "ingredient": "1 teaspoon ground cinnamon" },
  { id: 390, recipe_id: 61, "ingredient": "1/4 cup unsalted butter" },
  { id: 391, recipe_id: 63, "ingredient": "1 cup all-purpose flour" },
  { id: 392, recipe_id: 63, "ingredient": "0.25 cup packed brown sugar" },
  { id: 393, recipe_id: 63, "ingredient": "0.5 cup chopped walnuts" },
  { id: 394, recipe_id: 63, "ingredient": "0.5 cup butter, melted" },
  { id: 395, recipe_id: 63, "ingredient": "2 cups sliced fresh strawberries" },
  { id: 396, recipe_id: 63, "ingredient": "1 cup white sugar" },
  { id: 397, recipe_id: 63, "ingredient": "6 tablespoons pasteurized liquid egg whites" },
  { id: 398, recipe_id: 63, "ingredient": "2 tablespoons lemon juice" },
  { id: 399, recipe_id: 63, "ingredient": "1 cup heavy whipping cream, whipped" },
  { id: 400, recipe_id: 64, "ingredient": "1 (14 ounce) can sweetened condensed milk" },
  { id: 401, recipe_id: 64, "ingredient": "1 (8 ounce) package cream cheese, softened" },
  { id: 402, recipe_id: 64, "ingredient": "1 (12 ounce) container frozen whipped topping, thawed" },
  { id: 403, recipe_id: 64, "ingredient": "1 (20 ounce) can crushed pineapple, drained" },
  { id: 404, recipe_id: 64, "ingredient": "1.5 cups chopped pecans" },
  { id: 405, recipe_id: 64, "ingredient": "2 (9 inch) prepared graham cracker crusts" },
  { id: 406, recipe_id: 65, "ingredient": "1/3 cup white sugar" },
  { id: 407, recipe_id: 65, "ingredient": "1 teaspoon instant coffee powder" },
  { id: 408, recipe_id: 65, "ingredient": "1 tablespoon unsweetened cocoa powder" },
  { id: 409, recipe_id: 65, "ingredient": "1 teaspoon pure vanilla extract" },
  { id: 410, recipe_id: 65, "ingredient": "3 tablespoons coffee liqueur" },
  { id: 411, recipe_id: 65, "ingredient": "2 cups cold heavy cream" },
  { id: 412, recipe_id: 65, "ingredient": "12 ounces mascarpone cheese or cream cheese" },
  { id: 413, recipe_id: 65, "ingredient": "4 (8 ounce) packages chocolate chip cookies (about 45), such as Tate’s Bake Shop Double Chocolate Chip Cookies" },
  { id: 414, recipe_id: 66, "ingredient": "4 cups coarsely chopped seedless watermelon" },
  { id: 415, recipe_id: 66, "ingredient": "4 cups seedless red grapes, halved" },
  { id: 416, recipe_id: 66, "ingredient": "2 tablespoons grated lemon zest" },
  { id: 417, recipe_id: 66, "ingredient": "2 tablespoons grated lime zest" },
  { id: 418, recipe_id: 67, "ingredient": "2 cups diced seeded watermelon" },
  { id: 419, recipe_id: 67, "ingredient": "1 avocado - peeled, pitted, and diced" },
  { id: 420, recipe_id: 67, "ingredient": "0.25 cup diced red onion" },
  { id: 421, recipe_id: 67, "ingredient": "2 tablespoons lemon juice" },
  { id: 422, recipe_id: 67, "ingredient": "0.5 habanero pepper, seeded and minced" },
  { id: 423, recipe_id: 67, "ingredient": "1.5 teaspoons dried parsley" },
  { id: 424, recipe_id: 67, "ingredient": "0.25 teaspoon salt, or to taste" },
  { id: 425, recipe_id: 68, "ingredient": "4 cups cubed watermelon" },
  { id: 426, recipe_id: 68, "ingredient": "4 cups fresh baby spinach, torn" },
  { id: 427, recipe_id: 68, "ingredient": "2 large avocados - peeled, pitted, and diced" },
  { id: 428, recipe_id: 68, "ingredient": "0.25 cup walnut oil" },
  { id: 429, recipe_id: 68, "ingredient": "0.25 cup olive oil" },
  { id: 430, recipe_id: 68, "ingredient": "1 lime, juiced" },
  { id: 431, recipe_id: 68, "ingredient": "0.5 teaspoon sweet paprika" },
  { id: 432, recipe_id: 71, "ingredient": "1\tTablespoon olive oil" },
  { id: 433, recipe_id: 71, "ingredient": "2\tpoblano peppers,thinly sliced" },
  { id: 434, recipe_id: 71, "ingredient": "1\tyellow or orange bell pepper, thinly sliced" },
  { id: 435, recipe_id: 71, "ingredient": "1\twhite onion, thinly sliced" },
  { id: 436, recipe_id: 71, "ingredient": "1 1/2\tteaspoon chili powder" },
  { id: 437, recipe_id: 71, "ingredient": "1/2 \tteaspoon ground cumin" },
  { id: 438, recipe_id: 71, "ingredient": "1/4 \tteaspoon garlic powder" },
  { id: 439, recipe_id: 71, "ingredient": "3/4\tteaspoon kosher salt" },
  { id: 440, recipe_id: 71, "ingredient": "1/2 \tteaspoon freshly ground black pepper" },
  { id: 441, recipe_id: 71, "ingredient": "2 1/2 \ttablespoons butter" },
  { id: 442, recipe_id: 71, "ingredient": "2\ttablespoons all-purpose flour" },
  { id: 443, recipe_id: 71, "ingredient": "1\t(10 ounce) can diced tomatoes and green chiles" },
  { id: 444, recipe_id: 71, "ingredient": "1 1/4 \tcup chicken broth" },
  { id: 445, recipe_id: 71, "ingredient": "2 1/2\tcups shredded rotisserie chicken" },
  { id: 446, recipe_id: 71, "ingredient": "1\t15 ounce can pinto beans, drained and rinsed" },
  { id: 447, recipe_id: 71, "ingredient": "2\tcups sharp Cheddar cheese, divided" },
  { id: 448, recipe_id: 71, "ingredient": "3\tcups broken tortilla chips" },
  { id: 449, recipe_id: 71, "ingredient": "Optional toppings such as lettuce, cilantro, sour cream, salsa and hot sauce" },
  { id: 450, recipe_id: 72, "ingredient": "1.5 cups sliced fresh strawberries" },
  { id: 451, recipe_id: 72, "ingredient": "2 tablespoons white sugar" },
  { id: 452, recipe_id: 72, "ingredient": "1 cup all-purpose flour" },
  { id: 453, recipe_id: 72, "ingredient": "2 tablespoons white sugar" },
  { id: 454, recipe_id: 72, "ingredient": "0.75 teaspoon baking powder" },
  { id: 455, recipe_id: 72, "ingredient": "0.125 teaspoon salt" },
  { id: 456, recipe_id: 72, "ingredient": "2 tablespoons butter" },
  { id: 457, recipe_id: 72, "ingredient": "3 tablespoons 2% milk" },
  { id: 458, recipe_id: 72, "ingredient": "1 egg yolk, beaten" },
  { id: 459, recipe_id: 72, "ingredient": "0.75 teaspoon lemon zest" },
  { id: 460, recipe_id: 72, "ingredient": "0.25 cup nonfat plain yogurt" },
  { id: 461, recipe_id: 72, "ingredient": "0.25 cup reduced-fat sour cream" },
  { id: 462, recipe_id: 72, "ingredient": "1 tablespoon agave nectar" },
  { id: 463, recipe_id: 72, "ingredient": "0.5 teaspoon lemon zest" },
  { id: 464, recipe_id: 72, "ingredient": "0.33333334326744 cup heavy whipping cream" },
  { id: 465, recipe_id: 72, "ingredient": "1 teaspoon white sugar" },
  { id: 466, recipe_id: 73, "ingredient": "12\tsourdough english muffins, cut into cubes" },
  { id: 467, recipe_id: 73, "ingredient": "10\tTablespoons butter, divided" },
  { id: 468, recipe_id: 73, "ingredient": "2\tTablespoons dijon mustard" },
  { id: 469, recipe_id: 73, "ingredient": "8\teggs" },
  { id: 470, recipe_id: 73, "ingredient": "1 1/4 \tcup half and half" },
  { id: 471, recipe_id: 73, "ingredient": "1 1/2\tteaspoon kosher salt" },
  { id: 472, recipe_id: 73, "ingredient": "3/4 \tteaspoon pepper" },
  { id: 473, recipe_id: 73, "ingredient": "1/2 \tpound deli sliced ham" },
  { id: 474, recipe_id: 73, "ingredient": "3\tcups grated swiss or gruyere cheese" },
  { id: 475, recipe_id: 73, "ingredient": "2\tcups milk" },
  { id: 476, recipe_id: 73, "ingredient": "4\tTablespoons all-purpose flour" },
  { id: 477, recipe_id: 73, "ingredient": "1/8\tteaspoon grated nutmeg" },
  { id: 478, recipe_id: 73, "ingredient": "3\ttablespoons grated parmesan cheese" },
  { id: 479, recipe_id: 74, "ingredient": "8 ounces short pasta (elbows, shells, fusilli)" },
  { id: 480, recipe_id: 74, "ingredient": "1 1/2 tablespoons unsalted butter" },
  { id: 481, recipe_id: 74, "ingredient": "2 1/2 tablespoons flour" },
  { id: 482, recipe_id: 74, "ingredient": "10 ounces evaporated milk" },
  { id: 483, recipe_id: 74, "ingredient": "1/2 teaspoons Worcestershire sauce" },
  { id: 484, recipe_id: 74, "ingredient": "1 1/2 teaspoons Dijon mustard" },
  { id: 485, recipe_id: 74, "ingredient": "Salt to taste" },
  { id: 486, recipe_id: 74, "ingredient": "1/4 cup plus 2 tablespoons grated Italian Cheddar (such as Sartore MontAmoré® Cheddar), divided" },
  { id: 487, recipe_id: 74, "ingredient": "1/4 cup plus 2 tablespoons grated Gruyère cheese, divided" },
  { id: 488, recipe_id: 74, "ingredient": "1/4 cup plus 2 tablespoons grated fontina, divided" },
  { id: 489, recipe_id: 74, "ingredient": "1/4 cup plus 2 tablespoons grated sharp Cheddar, divided" },
  { id: 490, recipe_id: 74, "ingredient": "2 (0.9 ounce) pieces Brie cheese, rind removed" },
  { id: 491, recipe_id: 74, "ingredient": "2 tablespoons grated Italian Cheddar" },
  { id: 492, recipe_id: 74, "ingredient": "2 tablespoons grated Gruyère cheese" },
  { id: 493, recipe_id: 74, "ingredient": "2 tablespoons fontina" },
  { id: 494, recipe_id: 74, "ingredient": "2 tablespoons grated sharp Cheddar" },
  { id: 495, recipe_id: 77, "ingredient": "2 cups dark chocolate chips (such as Ghriradelli® 60% Cacao Bittersweet Chocolate Chips)" },
  { id: 496, recipe_id: 77, "ingredient": "1 1/2 cups white sugar" },
  { id: 497, recipe_id: 77, "ingredient": "1/4 cup water" },
  { id: 498, recipe_id: 77, "ingredient": "3 tablespoons light corn syrup" },
  { id: 499, recipe_id: 77, "ingredient": "1/4 teaspoon salt" },
  { id: 500, recipe_id: 77, "ingredient": "1 1/2 cups heavy cream" },
  { id: 501, recipe_id: 77, "ingredient": "2 teaspoons vanilla extract" },
  { id: 502, recipe_id: 77, "ingredient": "3 tablespoons Irish Cream liqueur (such as Bailey's)" },
  { id: 503, recipe_id: 77, "ingredient": "3 tablespoons unsalted butter" },
  { id: 504, recipe_id: 77, "ingredient": "1 (11.2 ounce) bottle stout beer (such as Guinness ™ )" },
  { id: 505, recipe_id: 77, "ingredient": "1 tablespoon dark brown sugar" },
  { id: 506, recipe_id: 77, "ingredient": "1 3/4 cups all-purpose flour" },
  { id: 507, recipe_id: 77, "ingredient": "1 cup unsweetened dark cocoa powder (such as Hershey's® Special Dark)" },
  { id: 508, recipe_id: 77, "ingredient": "1 teaspoon baking powder" },
  { id: 509, recipe_id: 77, "ingredient": "1 teaspoon baking soda" },
  { id: 510, recipe_id: 77, "ingredient": "3/4 teaspoon salt" },
  { id: 511, recipe_id: 77, "ingredient": "1/2 cup unsalted butter, softened" },
  { id: 512, recipe_id: 77, "ingredient": "3 tablespoons vegetable oil" },
  { id: 513, recipe_id: 77, "ingredient": "1 cup firmly packed dark brown sugar" },
  { id: 514, recipe_id: 77, "ingredient": "1/2 cup white sugar" },
  { id: 515, recipe_id: 77, "ingredient": "2 large eggs, room temp" },
  { id: 516, recipe_id: 77, "ingredient": "1 cup full-fat sour cream, at room temperature" },
  { id: 517, recipe_id: 77, "ingredient": "2 teaspoons vanilla extract" },
  { id: 518, recipe_id: 78, "ingredient": "2 large zucchini, trimmed and halved lengthwise" },
  { id: 519, recipe_id: 78, "ingredient": "4 ripe tomatoes, cored" },
  { id: 520, recipe_id: 78, "ingredient": "4 fresh basil leaves" },
  { id: 521, recipe_id: 78, "ingredient": "0.25 cup olive oil" },
  { id: 522, recipe_id: 78, "ingredient": "1 teaspoon crushed garlic" },
  { id: 523, recipe_id: 78, "ingredient": "1 teaspoon dried Italian herb seasoning" },
  { id: 524, recipe_id: 78, "ingredient": "1 teaspoon white sugar" },
  { id: 525, recipe_id: 78, "ingredient": "0.75 teaspoon salt" },
  { id: 526, recipe_id: 78, "ingredient": "0.5 teaspoon ground black pepper" },
  { id: 527, recipe_id: 78, "ingredient": "3 tablespoons olive oil" },
  { id: 528, recipe_id: 78, "ingredient": "1 onion, diced" },
  { id: 529, recipe_id: 78, "ingredient": "1 pound bulk sweet Italian sausage" },
  { id: 530, recipe_id: 78, "ingredient": "0.25 cup grated Parmesan cheese" },
  { id: 531, recipe_id: 78, "ingredient": "1 cup grated mozzarella cheese" },

];

export const directionsData: Direction[] = [
  { id: 361, recipe_id: 1, instruction: "Combine diced tomatoes, olive oil, and garlic in a bowl." },
  { id: 362, recipe_id: 1, instruction: "Toast bread slices and top with tomato mixture." },
  { id: 363, recipe_id: 1, instruction: "Garnish with basil leaves and serve." },

  { id: 364, recipe_id: 2, instruction: "Preheat oven to 375°F (190°C)." },
  { id: 365, recipe_id: 2, instruction: "Remove stems from mushrooms and fill caps with breadcrumbs and cheese." },
  { id: 366, recipe_id: 2, instruction: "Bake for 15 minutes until golden." },

  { id: 367, recipe_id: 3, instruction: "Skewer tomatoes, mozzarella, and basil onto toothpicks." },
  { id: 368, recipe_id: 3, instruction: "Drizzle with olive oil and balsamic glaze." },
  { id: 369, recipe_id: 3, instruction: "Serve chilled." },


  { id: 370, recipe_id: 4, instruction: "Mix lemon juice, water, and sugar in a pitcher." },
  { id: 371, recipe_id: 4, instruction: "Stir until sugar dissolves." },
  { id: 372, recipe_id: 4, instruction: "Serve over ice with lemon slices." },

  { id: 370, recipe_id: 4, instruction: "Mix lemon juice, water, and sugar in a pitcher." },
  { id: 371, recipe_id: 4, instruction: "Stir until sugar dissolves." },
  { id: 372, recipe_id: 4, instruction: "Serve over ice with lemon slices." },
]

export const nutritionData: Nutrition[] = [
  { recipe_id: 1 },
  { id: 1, recipe_id: 2, calories: "589 kcal", fat: "38", saturated_fat: "11", unsaturated_fat: "0", carbs: "17", fiber: "1", sugar: "0", cholesterol: "175", protein: "43", sodium: "1748" },
  { recipe_id: 3 },
  { id: 2, recipe_id: 4, calories: "423 kcal", fat: "19", saturated_fat: "6", unsaturated_fat: "0", carbs: "57", fiber: "4", sugar: "8", cholesterol: "75", protein: "10", sodium: "457" },
  { id: 3, recipe_id: 5, calories: "252 kcal", fat: "16", saturated_fat: "4", unsaturated_fat: "0", carbs: "22", fiber: "2", sugar: "3", cholesterol: "91", protein: "6", sodium: "307" },
  { id: 4, recipe_id: 6, calories: "209 kcal", fat: "1", saturated_fat: "0", unsaturated_fat: "0", carbs: "48", fiber: "2", sugar: "30", cholesterol: "2", protein: "3", sodium: "269" },
  { id: 5, recipe_id: 7, calories: "108 kcal", fat: "0", saturated_fat: "0", unsaturated_fat: "0", carbs: "29", fiber: "1", sugar: "26", cholesterol: "0", protein: "0", sodium: "8" },
  { id: 6, recipe_id: 8, calories: "261 kcal", fat: "16", saturated_fat: "8", unsaturated_fat: "0", carbs: "30", fiber: "2", sugar: "21", cholesterol: "51", protein: "3", sodium: "166" },
  { id: 7, recipe_id: 9, calories: "113 kcal", fat: "9", saturated_fat: "1", unsaturated_fat: "0", carbs: "8", fiber: "2", sugar: "3", cholesterol: "0", protein: "2", sodium: "203" },
  { id: 8, recipe_id: 10, calories: "150 kcal", fat: "14", saturated_fat: "9", unsaturated_fat: "0", carbs: "7", fiber: "0", sugar: "0", cholesterol: "40", protein: "1", sodium: "19" },
  { recipe_id: 11 },
  { id: 9, recipe_id: 12, calories: "215 kcal", fat: "13", saturated_fat: "8", unsaturated_fat: "0", carbs: "25", fiber: "0", sugar: "25", cholesterol: "41", protein: "0", sodium: "97" },
  { recipe_id: 13 },
  { id: 10, recipe_id: 14, calories: "81 kcal", fat: "0", saturated_fat: "0", unsaturated_fat: "0", carbs: "21", fiber: "1", sugar: "12", cholesterol: "0", protein: "0", sodium: "6" },
  { id: 11, recipe_id: 15, calories: "292 kcal", fat: "9", saturated_fat: "6", unsaturated_fat: "0", carbs: "33", fiber: "3", sugar: "5", cholesterol: "36", protein: "19", sodium: "367" },
  { recipe_id: 16 },
  { recipe_id: 17 },
  { recipe_id: 18 },
  { id: 12, recipe_id: 19, calories: "166 kcal", fat: "7", saturated_fat: "3", unsaturated_fat: "0", carbs: "27", fiber: "0", sugar: "23", cholesterol: "12", protein: "2", sodium: "74" },
  { id: 13, recipe_id: 20, calories: "77 kcal", fat: "4", saturated_fat: "2", unsaturated_fat: "0", carbs: "9", fiber: "0", sugar: "0", cholesterol: "17", protein: "1", sodium: "79" },
  { id: 14, recipe_id: 21, calories: "487 kcal", fat: "28", saturated_fat: "12", unsaturated_fat: "0", carbs: "57", fiber: "0", sugar: "0", cholesterol: "83", protein: "3", sodium: "280" },
  { recipe_id: 22 },
  { id: 15, recipe_id: 23, calories: "660 kcal", fat: "8", saturated_fat: "2", unsaturated_fat: "0", carbs: "99", fiber: "4", sugar: "21", cholesterol: "99", protein: "48", sodium: "115" },
  { id: 16, recipe_id: 24, calories: "375 kcal", fat: "17", saturated_fat: "3", unsaturated_fat: "0", carbs: "49", fiber: "4", sugar: "0", cholesterol: "1", protein: "9", sodium: "429" },
  { id: 17, recipe_id: 25, calories: "89 kcal", fat: "4", saturated_fat: "1", unsaturated_fat: "0", carbs: "14", fiber: "2", sugar: "0", cholesterol: "0", protein: "1", sodium: "126" },
  { id: 18, recipe_id: 26, calories: "276 kcal", fat: "10", saturated_fat: "1", unsaturated_fat: "0", carbs: "43", fiber: "2", sugar: "0", cholesterol: "0", protein: "4", sodium: "670" },
  { id: 19, recipe_id: 27, calories: "268 kcal", fat: "20", saturated_fat: "5", unsaturated_fat: "0", carbs: "16", fiber: "1", sugar: "2", cholesterol: "128", protein: "8", sodium: "692" },
  { id: 20, recipe_id: 28, calories: "260 kcal", fat: "16", saturated_fat: "9", unsaturated_fat: "0", carbs: "26", fiber: "1", sugar: "20", cholesterol: "89", protein: "4", sodium: "160" },
  { id: 21, recipe_id: 29, calories: "537 kcal", fat: "36", saturated_fat: "22", unsaturated_fat: "0", carbs: "51", fiber: "3", sugar: "31", cholesterol: "221", protein: "6", sodium: "293" },
  { id: 22, recipe_id: 30, calories: "513 kcal", fat: "7", saturated_fat: "4", unsaturated_fat: "0", carbs: "111", fiber: "3", sugar: "84", cholesterol: "18", protein: "5", sodium: "372" },
  { id: 23, recipe_id: 31, calories: "540 kcal", fat: "30", saturated_fat: "17", unsaturated_fat: "0", carbs: "30", fiber: "3", sugar: "6", cholesterol: "314", protein: "32", sodium: "1148" },
  { id: 24, recipe_id: 32, calories: "224 kcal", fat: "0", saturated_fat: "0", unsaturated_fat: "0", carbs: "32", fiber: "1", sugar: "0", cholesterol: "0", protein: "0", sodium: "17" },
  { id: 25, recipe_id: 33, calories: "386 kcal", fat: "14", saturated_fat: "6", unsaturated_fat: "0", carbs: "60", fiber: "1", sugar: "0", cholesterol: "68", protein: "6", sodium: "300" },
  { id: 26, recipe_id: 34, calories: "262 kcal", fat: "0", saturated_fat: "0", unsaturated_fat: "0", carbs: "69", fiber: "2", sugar: "0", cholesterol: "0", protein: "1", sodium: "9" },
  { id: 27, recipe_id: 35, calories: "69 kcal", fat: "7", saturated_fat: "1", unsaturated_fat: "0", carbs: "2", fiber: "0", sugar: "1", cholesterol: "4", protein: "0", sodium: "134" },
  { recipe_id: 36 },
  { id: 28, recipe_id: 37, calories: "83 kcal", fat: "1", saturated_fat: "1", unsaturated_fat: "0", carbs: "17", fiber: "2", sugar: "0", cholesterol: "4", protein: "3", sodium: "788" },
  { id: 29, recipe_id: 38, calories: "165 kcal", fat: "16", saturated_fat: "3", unsaturated_fat: "0", carbs: "3", fiber: "1", sugar: "0", cholesterol: "4", protein: "4", sodium: "143" },
  { id: 30, recipe_id: 39, calories: "117 kcal", fat: "8", saturated_fat: "1", unsaturated_fat: "0", carbs: "10", fiber: "2", sugar: "3", cholesterol: "4", protein: "2", sodium: "158" },
  { id: 31, recipe_id: 40, calories: "334 kcal", fat: "8", saturated_fat: "1", unsaturated_fat: "0", carbs: "55", fiber: "4", sugar: "3", cholesterol: "93", protein: "10", sodium: "162" },
  { recipe_id: 41 },
  { id: 32, recipe_id: 42, calories: "176 kcal", fat: "8", saturated_fat: "3", unsaturated_fat: "0", carbs: "24", fiber: "1", sugar: "0", cholesterol: "86", protein: "4", sodium: "114" },
  { id: 33, recipe_id: 43, calories: "606 kcal", fat: "35", saturated_fat: "14", unsaturated_fat: "0", carbs: "7", fiber: "1", sugar: "0", cholesterol: "194", protein: "64", sodium: "1775" },
  { recipe_id: 44 },
  { recipe_id: 45 },
  { id: 34, recipe_id: 46, calories: "546 kcal", fat: "38", saturated_fat: "19", unsaturated_fat: "0", carbs: "32", fiber: "1", sugar: "5", cholesterol: "88", protein: "19", sodium: "1068" },
  { id: 35, recipe_id: 47, calories: "211 kcal", fat: "12", saturated_fat: "3", unsaturated_fat: "0", carbs: "23", fiber: "6", sugar: "2", cholesterol: "5", protein: "6", sodium: "394" },
  { id: 36, recipe_id: 48, calories: "473 kcal", fat: "26", saturated_fat: "12", unsaturated_fat: "0", carbs: "28", fiber: "3", sugar: "4", cholesterol: "101", protein: "31", sodium: "1282" },
  { id: 37, recipe_id: 49, calories: "151 kcal", fat: "4", saturated_fat: "3", unsaturated_fat: "0", carbs: "28", fiber: "1", sugar: "25", cholesterol: "8", protein: "1", sodium: "1176" },
  { id: 38, recipe_id: 50, calories: "327 kcal", fat: "17", saturated_fat: "6", unsaturated_fat: "0", carbs: "34", fiber: "2", sugar: "8", cholesterol: "46", protein: "10", sodium: "657" },
  { id: 39, recipe_id: 51, calories: "271 kcal", fat: "9", saturated_fat: "2", unsaturated_fat: "0", carbs: "48", fiber: "2", sugar: "35", cholesterol: "25", protein: "3", sodium: "133" },
  { recipe_id: 52 },
  { recipe_id: 53 },
  { recipe_id: 54 },
  { recipe_id: 55 },
  { recipe_id: 56 },
  { recipe_id: 57 },
  { recipe_id: 58 },
  { recipe_id: 59 },
  { recipe_id: 60 },
  { id: 40, recipe_id: 61, calories: "489 kcal", fat: "25", saturated_fat: "11", unsaturated_fat: "0", carbs: "63", fiber: "2", sugar: "32", cholesterol: "55", protein: "5", sodium: "292" },
  { recipe_id: 62 },
  { id: 41, recipe_id: 63, calories: "89 kcal", fat: "5", saturated_fat: "3", unsaturated_fat: "0", carbs: "11", fiber: "0", sugar: "8", cholesterol: "11", protein: "1", sodium: "24" },
  { id: 42, recipe_id: 64, calories: "434 kcal", fat: "27", saturated_fat: "11", unsaturated_fat: "0", carbs: "45", fiber: "2", sugar: "35", cholesterol: "24", protein: "6", sodium: "249" },
  { id: 43, recipe_id: 65, calories: "678 kcal", fat: "53", saturated_fat: "29", unsaturated_fat: "0", carbs: "46", fiber: "2", sugar: "40", cholesterol: "159", protein: "6", sodium: "419" },
  { id: 44, recipe_id: 66, calories: "162 kcal", fat: "1", saturated_fat: "0", unsaturated_fat: "0", carbs: "41", fiber: "3", sugar: "37", cholesterol: "0", protein: "2", sodium: "5" },
  { id: 45, recipe_id: 67, calories: "88 kcal", fat: "6", saturated_fat: "1", unsaturated_fat: "0", carbs: "9", fiber: "3", sugar: "5", cholesterol: "0", protein: "1", sodium: "121" },
  { id: 46, recipe_id: 68, calories: "350 kcal", fat: "32", saturated_fat: "4", unsaturated_fat: "0", carbs: "18", fiber: "8", sugar: "7", cholesterol: "0", protein: "3", sodium: "24" },
  { recipe_id: 69 },
  { recipe_id: 70 },
  { id: 47, recipe_id: 71, calories: "775 kcal", fat: "49", saturated_fat: "21", unsaturated_fat: "0", carbs: "37", fiber: "2", sugar: "2", cholesterol: "204", protein: "51", sodium: "1741" },
  { id: 48, recipe_id: 72, calories: "738 kcal", fat: "34", saturated_fat: "20", unsaturated_fat: "0", carbs: "99", fiber: "5", sugar: "44", cholesterol: "202", protein: "13", sodium: "477" },
  { id: 49, recipe_id: 73, calories: "652 kcal", fat: "41", saturated_fat: "18", unsaturated_fat: "0", carbs: "44", fiber: "1", sugar: "24", cholesterol: "259", protein: "27", sodium: "1267" },
  { id: 50, recipe_id: 74, calories: "258 kcal", fat: "16", saturated_fat: "10", unsaturated_fat: "0", carbs: "15", fiber: "1", sugar: "4", cholesterol: "52", protein: "13", sodium: "300" },
  { recipe_id: 75 },
  { recipe_id: 76 },
  { id: 51, recipe_id: 77, calories: "760 kcal", fat: "39", saturated_fat: "21", unsaturated_fat: "0", carbs: "92", fiber: "4", sugar: "70", cholesterol: "106", protein: "7", sodium: "366" },
  { id: 52, recipe_id: 78, calories: "654 kcal", fat: "52", saturated_fat: "15", unsaturated_fat: "0", carbs: "23", fiber: "5", sugar: "11", cholesterol: "67", protein: "28", sodium: "1658" },
]
